// Code generated by package maintainer. DO NOT EDIT.
// Color names and values from xkcd's color name survey.
// https://xkcd.com/color/rgb/
// This package is licenced under the same license as the source:
// CC0 1.0 public domain. https://creativecommons.org/publicdomain/zero/1.0/

// Package xkcdcolors provides named colors from xkcd's color name survey.
package xkcdcolors

import "image/color"

var (
	
	// 1 cloudy blue #acc2d9 
	CloudyBlue = color.RGBA{R: 0xac, G: 0xc2, B: 0xd9, A:0xff }
	
	// 2 dark pastel green #56ae57 
	DarkPastelGreen = color.RGBA{R: 0x56, G: 0xae, B: 0x57, A:0xff }
	
	// 3 dust #b2996e 
	Dust = color.RGBA{R: 0xb2, G: 0x99, B: 0x6e, A:0xff }
	
	// 4 electric lime #a8ff04 
	ElectricLime = color.RGBA{R: 0xa8, G: 0xff, B: 0x04, A:0xff }
	
	// 5 fresh green #69d84f 
	FreshGreen = color.RGBA{R: 0x69, G: 0xd8, B: 0x4f, A:0xff }
	
	// 6 light eggplant #894585 
	LightEggplant = color.RGBA{R: 0x89, G: 0x45, B: 0x85, A:0xff }
	
	// 7 nasty green #70b23f 
	NastyGreen = color.RGBA{R: 0x70, G: 0xb2, B: 0x3f, A:0xff }
	
	// 8 really light blue #d4ffff 
	ReallyLightBlue = color.RGBA{R: 0xd4, G: 0xff, B: 0xff, A:0xff }
	
	// 9 tea #65ab7c 
	Tea = color.RGBA{R: 0x65, G: 0xab, B: 0x7c, A:0xff }
	
	// 10 warm purple #952e8f 
	WarmPurple = color.RGBA{R: 0x95, G: 0x2e, B: 0x8f, A:0xff }
	
	// 11 yellowish tan #fcfc81 
	YellowishTan = color.RGBA{R: 0xfc, G: 0xfc, B: 0x81, A:0xff }
	
	// 12 cement #a5a391 
	Cement = color.RGBA{R: 0xa5, G: 0xa3, B: 0x91, A:0xff }
	
	// 13 dark grass green #388004 
	DarkGrassGreen = color.RGBA{R: 0x38, G: 0x80, B: 0x04, A:0xff }
	
	// 14 dusty teal #4c9085 
	DustyTeal = color.RGBA{R: 0x4c, G: 0x90, B: 0x85, A:0xff }
	
	// 15 grey teal #5e9b8a 
	GreyTeal = color.RGBA{R: 0x5e, G: 0x9b, B: 0x8a, A:0xff }
	
	// 16 macaroni and cheese #efb435 
	MacaroniAndCheese = color.RGBA{R: 0xef, G: 0xb4, B: 0x35, A:0xff }
	
	// 17 pinkish tan #d99b82 
	PinkishTan = color.RGBA{R: 0xd9, G: 0x9b, B: 0x82, A:0xff }
	
	// 18 spruce #0a5f38 
	Spruce = color.RGBA{R: 0x0a, G: 0x5f, B: 0x38, A:0xff }
	
	// 19 strong blue #0c06f7 
	StrongBlue = color.RGBA{R: 0x0c, G: 0x06, B: 0xf7, A:0xff }
	
	// 20 toxic green #61de2a 
	ToxicGreen = color.RGBA{R: 0x61, G: 0xde, B: 0x2a, A:0xff }
	
	// 21 windows blue #3778bf 
	WindowsBlue = color.RGBA{R: 0x37, G: 0x78, B: 0xbf, A:0xff }
	
	// 22 blue blue #2242c7 
	BlueBlue = color.RGBA{R: 0x22, G: 0x42, B: 0xc7, A:0xff }
	
	// 23 blue with a hint of purple #533cc6 
	BlueWithAHintOfPurple = color.RGBA{R: 0x53, G: 0x3c, B: 0xc6, A:0xff }
	
	// 24 booger #9bb53c 
	Booger = color.RGBA{R: 0x9b, G: 0xb5, B: 0x3c, A:0xff }
	
	// 25 bright sea green #05ffa6 
	BrightSeaGreen = color.RGBA{R: 0x05, G: 0xff, B: 0xa6, A:0xff }
	
	// 26 dark green blue #1f6357 
	DarkGreenBlue = color.RGBA{R: 0x1f, G: 0x63, B: 0x57, A:0xff }
	
	// 27 deep turquoise #017374 
	DeepTurquoise = color.RGBA{R: 0x01, G: 0x73, B: 0x74, A:0xff }
	
	// 28 green teal #0cb577 
	GreenTeal = color.RGBA{R: 0x0c, G: 0xb5, B: 0x77, A:0xff }
	
	// 29 strong pink #ff0789 
	StrongPink = color.RGBA{R: 0xff, G: 0x07, B: 0x89, A:0xff }
	
	// 30 bland #afa88b 
	Bland = color.RGBA{R: 0xaf, G: 0xa8, B: 0x8b, A:0xff }
	
	// 31 deep aqua #08787f 
	DeepAqua = color.RGBA{R: 0x08, G: 0x78, B: 0x7f, A:0xff }
	
	// 32 lavender pink #dd85d7 
	LavenderPink = color.RGBA{R: 0xdd, G: 0x85, B: 0xd7, A:0xff }
	
	// 33 light moss green #a6c875 
	LightMossGreen = color.RGBA{R: 0xa6, G: 0xc8, B: 0x75, A:0xff }
	
	// 34 light seafoam green #a7ffb5 
	LightSeafoamGreen = color.RGBA{R: 0xa7, G: 0xff, B: 0xb5, A:0xff }
	
	// 35 olive yellow #c2b709 
	OliveYellow = color.RGBA{R: 0xc2, G: 0xb7, B: 0x09, A:0xff }
	
	// 36 pig pink #e78ea5 
	PigPink = color.RGBA{R: 0xe7, G: 0x8e, B: 0xa5, A:0xff }
	
	// 37 deep lilac #966ebd 
	DeepLilac = color.RGBA{R: 0x96, G: 0x6e, B: 0xbd, A:0xff }
	
	// 38 desert #ccad60 
	Desert = color.RGBA{R: 0xcc, G: 0xad, B: 0x60, A:0xff }
	
	// 39 dusty lavender #ac86a8 
	DustyLavender = color.RGBA{R: 0xac, G: 0x86, B: 0xa8, A:0xff }
	
	// 40 purpley grey #947e94 
	PurpleyGrey = color.RGBA{R: 0x94, G: 0x7e, B: 0x94, A:0xff }
	
	// 41 purply #983fb2 
	Purply = color.RGBA{R: 0x98, G: 0x3f, B: 0xb2, A:0xff }
	
	// 42 candy pink #ff63e9 
	CandyPink = color.RGBA{R: 0xff, G: 0x63, B: 0xe9, A:0xff }
	
	// 43 light pastel green #b2fba5 
	LightPastelGreen = color.RGBA{R: 0xb2, G: 0xfb, B: 0xa5, A:0xff }
	
	// 44 boring green #63b365 
	BoringGreen = color.RGBA{R: 0x63, G: 0xb3, B: 0x65, A:0xff }
	
	// 45 kiwi green #8ee53f 
	KiwiGreen = color.RGBA{R: 0x8e, G: 0xe5, B: 0x3f, A:0xff }
	
	// 46 light grey green #b7e1a1 
	LightGreyGreen = color.RGBA{R: 0xb7, G: 0xe1, B: 0xa1, A:0xff }
	
	// 47 orange pink #ff6f52 
	OrangePink = color.RGBA{R: 0xff, G: 0x6f, B: 0x52, A:0xff }
	
	// 48 tea green #bdf8a3 
	TeaGreen = color.RGBA{R: 0xbd, G: 0xf8, B: 0xa3, A:0xff }
	
	// 49 very light brown #d3b683 
	VeryLightBrown = color.RGBA{R: 0xd3, G: 0xb6, B: 0x83, A:0xff }
	
	// 50 egg shell #fffcc4 
	EggShell = color.RGBA{R: 0xff, G: 0xfc, B: 0xc4, A:0xff }
	
	// 51 eggplant purple #430541 
	EggplantPurple = color.RGBA{R: 0x43, G: 0x05, B: 0x41, A:0xff }
	
	// 52 powder pink #ffb2d0 
	PowderPink = color.RGBA{R: 0xff, G: 0xb2, B: 0xd0, A:0xff }
	
	// 53 reddish grey #997570 
	ReddishGrey = color.RGBA{R: 0x99, G: 0x75, B: 0x70, A:0xff }
	
	// 54 baby shit brown #ad900d 
	BabyShitBrown = color.RGBA{R: 0xad, G: 0x90, B: 0x0d, A:0xff }
	
	// 55 liliac #c48efd 
	Liliac = color.RGBA{R: 0xc4, G: 0x8e, B: 0xfd, A:0xff }
	
	// 56 stormy blue #507b9c 
	StormyBlue = color.RGBA{R: 0x50, G: 0x7b, B: 0x9c, A:0xff }
	
	// 57 ugly brown #7d7103 
	UglyBrown = color.RGBA{R: 0x7d, G: 0x71, B: 0x03, A:0xff }
	
	// 58 custard #fffd78 
	Custard = color.RGBA{R: 0xff, G: 0xfd, B: 0x78, A:0xff }
	
	// 59 darkish pink #da467d 
	DarkishPink = color.RGBA{R: 0xda, G: 0x46, B: 0x7d, A:0xff }
	
	// 60 deep brown #410200 
	DeepBrown = color.RGBA{R: 0x41, G: 0x02, B: 0x00, A:0xff }
	
	// 61 greenish beige #c9d179 
	GreenishBeige = color.RGBA{R: 0xc9, G: 0xd1, B: 0x79, A:0xff }
	
	// 62 manilla #fffa86 
	Manilla = color.RGBA{R: 0xff, G: 0xfa, B: 0x86, A:0xff }
	
	// 63 off blue #5684ae 
	OffBlue = color.RGBA{R: 0x56, G: 0x84, B: 0xae, A:0xff }
	
	// 64 battleship grey #6b7c85 
	BattleshipGrey = color.RGBA{R: 0x6b, G: 0x7c, B: 0x85, A:0xff }
	
	// 65 browny green #6f6c0a 
	BrownyGreen = color.RGBA{R: 0x6f, G: 0x6c, B: 0x0a, A:0xff }
	
	// 66 bruise #7e4071 
	Bruise = color.RGBA{R: 0x7e, G: 0x40, B: 0x71, A:0xff }
	
	// 67 kelley green #009337 
	KelleyGreen = color.RGBA{R: 0x00, G: 0x93, B: 0x37, A:0xff }
	
	// 68 sickly yellow #d0e429 
	SicklyYellow = color.RGBA{R: 0xd0, G: 0xe4, B: 0x29, A:0xff }
	
	// 69 sunny yellow #fff917 
	SunnyYellow = color.RGBA{R: 0xff, G: 0xf9, B: 0x17, A:0xff }
	
	// 70 azul #1d5dec 
	Azul = color.RGBA{R: 0x1d, G: 0x5d, B: 0xec, A:0xff }
	
	// 71 darkgreen #054907 
	Darkgreen = color.RGBA{R: 0x05, G: 0x49, B: 0x07, A:0xff }
	
	// 72 green/yellow #b5ce08 
	Green_Yellow = color.RGBA{R: 0xb5, G: 0xce, B: 0x08, A:0xff }
	
	// 73 lichen #8fb67b 
	Lichen = color.RGBA{R: 0x8f, G: 0xb6, B: 0x7b, A:0xff }
	
	// 74 light light green #c8ffb0 
	LightLightGreen = color.RGBA{R: 0xc8, G: 0xff, B: 0xb0, A:0xff }
	
	// 75 pale gold #fdde6c 
	PaleGold = color.RGBA{R: 0xfd, G: 0xde, B: 0x6c, A:0xff }
	
	// 76 sun yellow #ffdf22 
	SunYellow = color.RGBA{R: 0xff, G: 0xdf, B: 0x22, A:0xff }
	
	// 77 tan green #a9be70 
	TanGreen = color.RGBA{R: 0xa9, G: 0xbe, B: 0x70, A:0xff }
	
	// 78 burple #6832e3 
	Burple = color.RGBA{R: 0x68, G: 0x32, B: 0xe3, A:0xff }
	
	// 79 butterscotch #fdb147 
	Butterscotch = color.RGBA{R: 0xfd, G: 0xb1, B: 0x47, A:0xff }
	
	// 80 toupe #c7ac7d 
	Toupe = color.RGBA{R: 0xc7, G: 0xac, B: 0x7d, A:0xff }
	
	// 81 dark cream #fff39a 
	DarkCream = color.RGBA{R: 0xff, G: 0xf3, B: 0x9a, A:0xff }
	
	// 82 indian red #850e04 
	IndianRed = color.RGBA{R: 0x85, G: 0x0e, B: 0x04, A:0xff }
	
	// 83 light lavendar #efc0fe 
	LightLavendar = color.RGBA{R: 0xef, G: 0xc0, B: 0xfe, A:0xff }
	
	// 84 poison green #40fd14 
	PoisonGreen = color.RGBA{R: 0x40, G: 0xfd, B: 0x14, A:0xff }
	
	// 85 baby puke green #b6c406 
	BabyPukeGreen = color.RGBA{R: 0xb6, G: 0xc4, B: 0x06, A:0xff }
	
	// 86 bright yellow green #9dff00 
	BrightYellowGreen = color.RGBA{R: 0x9d, G: 0xff, B: 0x00, A:0xff }
	
	// 87 charcoal grey #3c4142 
	CharcoalGrey = color.RGBA{R: 0x3c, G: 0x41, B: 0x42, A:0xff }
	
	// 88 squash #f2ab15 
	Squash = color.RGBA{R: 0xf2, G: 0xab, B: 0x15, A:0xff }
	
	// 89 cinnamon #ac4f06 
	Cinnamon = color.RGBA{R: 0xac, G: 0x4f, B: 0x06, A:0xff }
	
	// 90 light pea green #c4fe82 
	LightPeaGreen = color.RGBA{R: 0xc4, G: 0xfe, B: 0x82, A:0xff }
	
	// 91 radioactive green #2cfa1f 
	RadioactiveGreen = color.RGBA{R: 0x2c, G: 0xfa, B: 0x1f, A:0xff }
	
	// 92 raw sienna #9a6200 
	RawSienna = color.RGBA{R: 0x9a, G: 0x62, B: 0x00, A:0xff }
	
	// 93 baby purple #ca9bf7 
	BabyPurple = color.RGBA{R: 0xca, G: 0x9b, B: 0xf7, A:0xff }
	
	// 94 cocoa #875f42 
	Cocoa = color.RGBA{R: 0x87, G: 0x5f, B: 0x42, A:0xff }
	
	// 95 light royal blue #3a2efe 
	LightRoyalBlue = color.RGBA{R: 0x3a, G: 0x2e, B: 0xfe, A:0xff }
	
	// 96 orangeish #fd8d49 
	Orangeish = color.RGBA{R: 0xfd, G: 0x8d, B: 0x49, A:0xff }
	
	// 97 rust brown #8b3103 
	RustBrown = color.RGBA{R: 0x8b, G: 0x31, B: 0x03, A:0xff }
	
	// 98 sand brown #cba560 
	SandBrown = color.RGBA{R: 0xcb, G: 0xa5, B: 0x60, A:0xff }
	
	// 99 swamp #698339 
	Swamp = color.RGBA{R: 0x69, G: 0x83, B: 0x39, A:0xff }
	
	// 100 tealish green #0cdc73 
	TealishGreen = color.RGBA{R: 0x0c, G: 0xdc, B: 0x73, A:0xff }
	
	// 101 burnt siena #b75203 
	BurntSiena = color.RGBA{R: 0xb7, G: 0x52, B: 0x03, A:0xff }
	
	// 102 camo #7f8f4e 
	Camo = color.RGBA{R: 0x7f, G: 0x8f, B: 0x4e, A:0xff }
	
	// 103 dusk blue #26538d 
	DuskBlue = color.RGBA{R: 0x26, G: 0x53, B: 0x8d, A:0xff }
	
	// 104 fern #63a950 
	Fern = color.RGBA{R: 0x63, G: 0xa9, B: 0x50, A:0xff }
	
	// 105 old rose #c87f89 
	OldRose = color.RGBA{R: 0xc8, G: 0x7f, B: 0x89, A:0xff }
	
	// 106 pale light green #b1fc99 
	PaleLightGreen = color.RGBA{R: 0xb1, G: 0xfc, B: 0x99, A:0xff }
	
	// 107 peachy pink #ff9a8a 
	PeachyPink = color.RGBA{R: 0xff, G: 0x9a, B: 0x8a, A:0xff }
	
	// 108 rosy pink #f6688e 
	RosyPink = color.RGBA{R: 0xf6, G: 0x68, B: 0x8e, A:0xff }
	
	// 109 light bluish green #76fda8 
	LightBluishGreen = color.RGBA{R: 0x76, G: 0xfd, B: 0xa8, A:0xff }
	
	// 110 light bright green #53fe5c 
	LightBrightGreen = color.RGBA{R: 0x53, G: 0xfe, B: 0x5c, A:0xff }
	
	// 111 light neon green #4efd54 
	LightNeonGreen = color.RGBA{R: 0x4e, G: 0xfd, B: 0x54, A:0xff }
	
	// 112 light seafoam #a0febf 
	LightSeafoam = color.RGBA{R: 0xa0, G: 0xfe, B: 0xbf, A:0xff }
	
	// 113 tiffany blue #7bf2da 
	TiffanyBlue = color.RGBA{R: 0x7b, G: 0xf2, B: 0xda, A:0xff }
	
	// 114 washed out green #bcf5a6 
	WashedOutGreen = color.RGBA{R: 0xbc, G: 0xf5, B: 0xa6, A:0xff }
	
	// 115 browny orange #ca6b02 
	BrownyOrange = color.RGBA{R: 0xca, G: 0x6b, B: 0x02, A:0xff }
	
	// 116 nice blue #107ab0 
	NiceBlue = color.RGBA{R: 0x10, G: 0x7a, B: 0xb0, A:0xff }
	
	// 117 sapphire #2138ab 
	Sapphire = color.RGBA{R: 0x21, G: 0x38, B: 0xab, A:0xff }
	
	// 118 greyish teal #719f91 
	GreyishTeal = color.RGBA{R: 0x71, G: 0x9f, B: 0x91, A:0xff }
	
	// 119 orangey yellow #fdb915 
	OrangeyYellow = color.RGBA{R: 0xfd, G: 0xb9, B: 0x15, A:0xff }
	
	// 120 parchment #fefcaf 
	Parchment = color.RGBA{R: 0xfe, G: 0xfc, B: 0xaf, A:0xff }
	
	// 121 straw #fcf679 
	Straw = color.RGBA{R: 0xfc, G: 0xf6, B: 0x79, A:0xff }
	
	// 122 very dark brown #1d0200 
	VeryDarkBrown = color.RGBA{R: 0x1d, G: 0x02, B: 0x00, A:0xff }
	
	// 123 terracota #cb6843 
	Terracota = color.RGBA{R: 0xcb, G: 0x68, B: 0x43, A:0xff }
	
	// 124 ugly blue #31668a 
	UglyBlue = color.RGBA{R: 0x31, G: 0x66, B: 0x8a, A:0xff }
	
	// 125 clear blue #247afd 
	ClearBlue = color.RGBA{R: 0x24, G: 0x7a, B: 0xfd, A:0xff }
	
	// 126 creme #ffffb6 
	Creme = color.RGBA{R: 0xff, G: 0xff, B: 0xb6, A:0xff }
	
	// 127 foam green #90fda9 
	FoamGreen = color.RGBA{R: 0x90, G: 0xfd, B: 0xa9, A:0xff }
	
	// 128 grey/green #86a17d 
	Grey_Green = color.RGBA{R: 0x86, G: 0xa1, B: 0x7d, A:0xff }
	
	// 129 light gold #fddc5c 
	LightGold = color.RGBA{R: 0xfd, G: 0xdc, B: 0x5c, A:0xff }
	
	// 130 seafoam blue #78d1b6 
	SeafoamBlue = color.RGBA{R: 0x78, G: 0xd1, B: 0xb6, A:0xff }
	
	// 131 topaz #13bbaf 
	Topaz = color.RGBA{R: 0x13, G: 0xbb, B: 0xaf, A:0xff }
	
	// 132 violet pink #fb5ffc 
	VioletPink = color.RGBA{R: 0xfb, G: 0x5f, B: 0xfc, A:0xff }
	
	// 133 wintergreen #20f986 
	Wintergreen = color.RGBA{R: 0x20, G: 0xf9, B: 0x86, A:0xff }
	
	// 134 yellow tan #ffe36e 
	YellowTan = color.RGBA{R: 0xff, G: 0xe3, B: 0x6e, A:0xff }
	
	// 135 dark fuchsia #9d0759 
	DarkFuchsia = color.RGBA{R: 0x9d, G: 0x07, B: 0x59, A:0xff }
	
	// 136 indigo blue #3a18b1 
	IndigoBlue = color.RGBA{R: 0x3a, G: 0x18, B: 0xb1, A:0xff }
	
	// 137 light yellowish green #c2ff89 
	LightYellowishGreen = color.RGBA{R: 0xc2, G: 0xff, B: 0x89, A:0xff }
	
	// 138 pale magenta #d767ad 
	PaleMagenta = color.RGBA{R: 0xd7, G: 0x67, B: 0xad, A:0xff }
	
	// 139 rich purple #720058 
	RichPurple = color.RGBA{R: 0x72, G: 0x00, B: 0x58, A:0xff }
	
	// 140 sunflower yellow #ffda03 
	SunflowerYellow = color.RGBA{R: 0xff, G: 0xda, B: 0x03, A:0xff }
	
	// 141 green/blue #01c08d 
	Green_Blue = color.RGBA{R: 0x01, G: 0xc0, B: 0x8d, A:0xff }
	
	// 142 leather #ac7434 
	Leather = color.RGBA{R: 0xac, G: 0x74, B: 0x34, A:0xff }
	
	// 143 racing green #014600 
	RacingGreen = color.RGBA{R: 0x01, G: 0x46, B: 0x00, A:0xff }
	
	// 144 vivid purple #9900fa 
	VividPurple = color.RGBA{R: 0x99, G: 0x00, B: 0xfa, A:0xff }
	
	// 145 dark royal blue #02066f 
	DarkRoyalBlue = color.RGBA{R: 0x02, G: 0x06, B: 0x6f, A:0xff }
	
	// 146 hazel #8e7618 
	Hazel = color.RGBA{R: 0x8e, G: 0x76, B: 0x18, A:0xff }
	
	// 147 muted pink #d1768f 
	MutedPink = color.RGBA{R: 0xd1, G: 0x76, B: 0x8f, A:0xff }
	
	// 148 booger green #96b403 
	BoogerGreen = color.RGBA{R: 0x96, G: 0xb4, B: 0x03, A:0xff }
	
	// 149 canary #fdff63 
	Canary = color.RGBA{R: 0xfd, G: 0xff, B: 0x63, A:0xff }
	
	// 150 cool grey #95a3a6 
	CoolGrey = color.RGBA{R: 0x95, G: 0xa3, B: 0xa6, A:0xff }
	
	// 151 dark taupe #7f684e 
	DarkTaupe = color.RGBA{R: 0x7f, G: 0x68, B: 0x4e, A:0xff }
	
	// 152 darkish purple #751973 
	DarkishPurple = color.RGBA{R: 0x75, G: 0x19, B: 0x73, A:0xff }
	
	// 153 true green #089404 
	TrueGreen = color.RGBA{R: 0x08, G: 0x94, B: 0x04, A:0xff }
	
	// 154 coral pink #ff6163 
	CoralPink = color.RGBA{R: 0xff, G: 0x61, B: 0x63, A:0xff }
	
	// 155 dark sage #598556 
	DarkSage = color.RGBA{R: 0x59, G: 0x85, B: 0x56, A:0xff }
	
	// 156 dark slate blue #214761 
	DarkSlateBlue = color.RGBA{R: 0x21, G: 0x47, B: 0x61, A:0xff }
	
	// 157 flat blue #3c73a8 
	FlatBlue = color.RGBA{R: 0x3c, G: 0x73, B: 0xa8, A:0xff }
	
	// 158 mushroom #ba9e88 
	Mushroom = color.RGBA{R: 0xba, G: 0x9e, B: 0x88, A:0xff }
	
	// 159 rich blue #021bf9 
	RichBlue = color.RGBA{R: 0x02, G: 0x1b, B: 0xf9, A:0xff }
	
	// 160 dirty purple #734a65 
	DirtyPurple = color.RGBA{R: 0x73, G: 0x4a, B: 0x65, A:0xff }
	
	// 161 greenblue #23c48b 
	Greenblue = color.RGBA{R: 0x23, G: 0xc4, B: 0x8b, A:0xff }
	
	// 162 icky green #8fae22 
	IckyGreen = color.RGBA{R: 0x8f, G: 0xae, B: 0x22, A:0xff }
	
	// 163 light khaki #e6f2a2 
	LightKhaki = color.RGBA{R: 0xe6, G: 0xf2, B: 0xa2, A:0xff }
	
	// 164 warm blue #4b57db 
	WarmBlue = color.RGBA{R: 0x4b, G: 0x57, B: 0xdb, A:0xff }
	
	// 165 dark hot pink #d90166 
	DarkHotPink = color.RGBA{R: 0xd9, G: 0x01, B: 0x66, A:0xff }
	
	// 166 deep sea blue #015482 
	DeepSeaBlue = color.RGBA{R: 0x01, G: 0x54, B: 0x82, A:0xff }
	
	// 167 carmine #9d0216 
	Carmine = color.RGBA{R: 0x9d, G: 0x02, B: 0x16, A:0xff }
	
	// 168 dark yellow green #728f02 
	DarkYellowGreen = color.RGBA{R: 0x72, G: 0x8f, B: 0x02, A:0xff }
	
	// 169 pale peach #ffe5ad 
	PalePeach = color.RGBA{R: 0xff, G: 0xe5, B: 0xad, A:0xff }
	
	// 170 plum purple #4e0550 
	PlumPurple = color.RGBA{R: 0x4e, G: 0x05, B: 0x50, A:0xff }
	
	// 171 golden rod #f9bc08 
	GoldenRod = color.RGBA{R: 0xf9, G: 0xbc, B: 0x08, A:0xff }
	
	// 172 neon red #ff073a 
	NeonRed = color.RGBA{R: 0xff, G: 0x07, B: 0x3a, A:0xff }
	
	// 173 old pink #c77986 
	OldPink = color.RGBA{R: 0xc7, G: 0x79, B: 0x86, A:0xff }
	
	// 174 very pale blue #d6fffe 
	VeryPaleBlue = color.RGBA{R: 0xd6, G: 0xff, B: 0xfe, A:0xff }
	
	// 175 blood orange #fe4b03 
	BloodOrange = color.RGBA{R: 0xfe, G: 0x4b, B: 0x03, A:0xff }
	
	// 176 grapefruit #fd5956 
	Grapefruit = color.RGBA{R: 0xfd, G: 0x59, B: 0x56, A:0xff }
	
	// 177 sand yellow #fce166 
	SandYellow = color.RGBA{R: 0xfc, G: 0xe1, B: 0x66, A:0xff }
	
	// 178 clay brown #b2713d 
	ClayBrown = color.RGBA{R: 0xb2, G: 0x71, B: 0x3d, A:0xff }
	
	// 179 dark blue grey #1f3b4d 
	DarkBlueGrey = color.RGBA{R: 0x1f, G: 0x3b, B: 0x4d, A:0xff }
	
	// 180 flat green #699d4c 
	FlatGreen = color.RGBA{R: 0x69, G: 0x9d, B: 0x4c, A:0xff }
	
	// 181 light green blue #56fca2 
	LightGreenBlue = color.RGBA{R: 0x56, G: 0xfc, B: 0xa2, A:0xff }
	
	// 182 warm pink #fb5581 
	WarmPink = color.RGBA{R: 0xfb, G: 0x55, B: 0x81, A:0xff }
	
	// 183 dodger blue #3e82fc 
	DodgerBlue = color.RGBA{R: 0x3e, G: 0x82, B: 0xfc, A:0xff }
	
	// 184 gross green #a0bf16 
	GrossGreen = color.RGBA{R: 0xa0, G: 0xbf, B: 0x16, A:0xff }
	
	// 185 ice #d6fffa 
	Ice = color.RGBA{R: 0xd6, G: 0xff, B: 0xfa, A:0xff }
	
	// 186 metallic blue #4f738e 
	MetallicBlue = color.RGBA{R: 0x4f, G: 0x73, B: 0x8e, A:0xff }
	
	// 187 pale salmon #ffb19a 
	PaleSalmon = color.RGBA{R: 0xff, G: 0xb1, B: 0x9a, A:0xff }
	
	// 188 sap green #5c8b15 
	SapGreen = color.RGBA{R: 0x5c, G: 0x8b, B: 0x15, A:0xff }
	
	// 189 algae #54ac68 
	Algae = color.RGBA{R: 0x54, G: 0xac, B: 0x68, A:0xff }
	
	// 190 bluey grey #89a0b0 
	BlueyGrey = color.RGBA{R: 0x89, G: 0xa0, B: 0xb0, A:0xff }
	
	// 191 greeny grey #7ea07a 
	GreenyGrey = color.RGBA{R: 0x7e, G: 0xa0, B: 0x7a, A:0xff }
	
	// 192 highlighter green #1bfc06 
	HighlighterGreen = color.RGBA{R: 0x1b, G: 0xfc, B: 0x06, A:0xff }
	
	// 193 light light blue #cafffb 
	LightLightBlue = color.RGBA{R: 0xca, G: 0xff, B: 0xfb, A:0xff }
	
	// 194 light mint #b6ffbb 
	LightMint = color.RGBA{R: 0xb6, G: 0xff, B: 0xbb, A:0xff }
	
	// 195 raw umber #a75e09 
	RawUmber = color.RGBA{R: 0xa7, G: 0x5e, B: 0x09, A:0xff }
	
	// 196 vivid blue #152eff 
	VividBlue = color.RGBA{R: 0x15, G: 0x2e, B: 0xff, A:0xff }
	
	// 197 deep lavender #8d5eb7 
	DeepLavender = color.RGBA{R: 0x8d, G: 0x5e, B: 0xb7, A:0xff }
	
	// 198 dull teal #5f9e8f 
	DullTeal = color.RGBA{R: 0x5f, G: 0x9e, B: 0x8f, A:0xff }
	
	// 199 light greenish blue #63f7b4 
	LightGreenishBlue = color.RGBA{R: 0x63, G: 0xf7, B: 0xb4, A:0xff }
	
	// 200 mud green #606602 
	MudGreen = color.RGBA{R: 0x60, G: 0x66, B: 0x02, A:0xff }
	
	// 201 pinky #fc86aa 
	Pinky = color.RGBA{R: 0xfc, G: 0x86, B: 0xaa, A:0xff }
	
	// 202 red wine #8c0034 
	RedWine = color.RGBA{R: 0x8c, G: 0x00, B: 0x34, A:0xff }
	
	// 203 shit green #758000 
	ShitGreen = color.RGBA{R: 0x75, G: 0x80, B: 0x00, A:0xff }
	
	// 204 tan brown #ab7e4c 
	TanBrown = color.RGBA{R: 0xab, G: 0x7e, B: 0x4c, A:0xff }
	
	// 205 darkblue #030764 
	Darkblue = color.RGBA{R: 0x03, G: 0x07, B: 0x64, A:0xff }
	
	// 206 rosa #fe86a4 
	Rosa = color.RGBA{R: 0xfe, G: 0x86, B: 0xa4, A:0xff }
	
	// 207 lipstick #d5174e 
	Lipstick = color.RGBA{R: 0xd5, G: 0x17, B: 0x4e, A:0xff }
	
	// 208 pale mauve #fed0fc 
	PaleMauve = color.RGBA{R: 0xfe, G: 0xd0, B: 0xfc, A:0xff }
	
	// 209 claret #680018 
	Claret = color.RGBA{R: 0x68, G: 0x00, B: 0x18, A:0xff }
	
	// 210 dandelion #fedf08 
	Dandelion = color.RGBA{R: 0xfe, G: 0xdf, B: 0x08, A:0xff }
	
	// 211 orangered #fe420f 
	Orangered = color.RGBA{R: 0xfe, G: 0x42, B: 0x0f, A:0xff }
	
	// 212 poop green #6f7c00 
	PoopGreen = color.RGBA{R: 0x6f, G: 0x7c, B: 0x00, A:0xff }
	
	// 213 ruby #ca0147 
	Ruby = color.RGBA{R: 0xca, G: 0x01, B: 0x47, A:0xff }
	
	// 214 dark #1b2431 
	Dark = color.RGBA{R: 0x1b, G: 0x24, B: 0x31, A:0xff }
	
	// 215 greenish turquoise #00fbb0 
	GreenishTurquoise = color.RGBA{R: 0x00, G: 0xfb, B: 0xb0, A:0xff }
	
	// 216 pastel red #db5856 
	PastelRed = color.RGBA{R: 0xdb, G: 0x58, B: 0x56, A:0xff }
	
	// 217 piss yellow #ddd618 
	PissYellow = color.RGBA{R: 0xdd, G: 0xd6, B: 0x18, A:0xff }
	
	// 218 bright cyan #41fdfe 
	BrightCyan = color.RGBA{R: 0x41, G: 0xfd, B: 0xfe, A:0xff }
	
	// 219 dark coral #cf524e 
	DarkCoral = color.RGBA{R: 0xcf, G: 0x52, B: 0x4e, A:0xff }
	
	// 220 algae green #21c36f 
	AlgaeGreen = color.RGBA{R: 0x21, G: 0xc3, B: 0x6f, A:0xff }
	
	// 221 darkish red #a90308 
	DarkishRed = color.RGBA{R: 0xa9, G: 0x03, B: 0x08, A:0xff }
	
	// 222 reddy brown #6e1005 
	ReddyBrown = color.RGBA{R: 0x6e, G: 0x10, B: 0x05, A:0xff }
	
	// 223 blush pink #fe828c 
	BlushPink = color.RGBA{R: 0xfe, G: 0x82, B: 0x8c, A:0xff }
	
	// 224 camouflage green #4b6113 
	CamouflageGreen = color.RGBA{R: 0x4b, G: 0x61, B: 0x13, A:0xff }
	
	// 225 lawn green #4da409 
	LawnGreen = color.RGBA{R: 0x4d, G: 0xa4, B: 0x09, A:0xff }
	
	// 226 putty #beae8a 
	Putty = color.RGBA{R: 0xbe, G: 0xae, B: 0x8a, A:0xff }
	
	// 227 vibrant blue #0339f8 
	VibrantBlue = color.RGBA{R: 0x03, G: 0x39, B: 0xf8, A:0xff }
	
	// 228 dark sand #a88f59 
	DarkSand = color.RGBA{R: 0xa8, G: 0x8f, B: 0x59, A:0xff }
	
	// 229 purple/blue #5d21d0 
	Purple_Blue = color.RGBA{R: 0x5d, G: 0x21, B: 0xd0, A:0xff }
	
	// 230 saffron #feb209 
	Saffron = color.RGBA{R: 0xfe, G: 0xb2, B: 0x09, A:0xff }
	
	// 231 twilight #4e518b 
	Twilight = color.RGBA{R: 0x4e, G: 0x51, B: 0x8b, A:0xff }
	
	// 232 warm brown #964e02 
	WarmBrown = color.RGBA{R: 0x96, G: 0x4e, B: 0x02, A:0xff }
	
	// 233 bluegrey #85a3b2 
	Bluegrey = color.RGBA{R: 0x85, G: 0xa3, B: 0xb2, A:0xff }
	
	// 234 bubble gum pink #ff69af 
	BubbleGumPink = color.RGBA{R: 0xff, G: 0x69, B: 0xaf, A:0xff }
	
	// 235 duck egg blue #c3fbf4 
	DuckEggBlue = color.RGBA{R: 0xc3, G: 0xfb, B: 0xf4, A:0xff }
	
	// 236 greenish cyan #2afeb7 
	GreenishCyan = color.RGBA{R: 0x2a, G: 0xfe, B: 0xb7, A:0xff }
	
	// 237 petrol #005f6a 
	Petrol = color.RGBA{R: 0x00, G: 0x5f, B: 0x6a, A:0xff }
	
	// 238 royal #0c1793 
	Royal = color.RGBA{R: 0x0c, G: 0x17, B: 0x93, A:0xff }
	
	// 239 butter #ffff81 
	Butter = color.RGBA{R: 0xff, G: 0xff, B: 0x81, A:0xff }
	
	// 240 dusty orange #f0833a 
	DustyOrange = color.RGBA{R: 0xf0, G: 0x83, B: 0x3a, A:0xff }
	
	// 241 off yellow #f1f33f 
	OffYellow = color.RGBA{R: 0xf1, G: 0xf3, B: 0x3f, A:0xff }
	
	// 242 pale olive green #b1d27b 
	PaleOliveGreen = color.RGBA{R: 0xb1, G: 0xd2, B: 0x7b, A:0xff }
	
	// 243 orangish #fc824a 
	Orangish = color.RGBA{R: 0xfc, G: 0x82, B: 0x4a, A:0xff }
	
	// 244 leaf #71aa34 
	Leaf = color.RGBA{R: 0x71, G: 0xaa, B: 0x34, A:0xff }
	
	// 245 light blue grey #b7c9e2 
	LightBlueGrey = color.RGBA{R: 0xb7, G: 0xc9, B: 0xe2, A:0xff }
	
	// 246 dried blood #4b0101 
	DriedBlood = color.RGBA{R: 0x4b, G: 0x01, B: 0x01, A:0xff }
	
	// 247 lightish purple #a552e6 
	LightishPurple = color.RGBA{R: 0xa5, G: 0x52, B: 0xe6, A:0xff }
	
	// 248 rusty red #af2f0d 
	RustyRed = color.RGBA{R: 0xaf, G: 0x2f, B: 0x0d, A:0xff }
	
	// 249 lavender blue #8b88f8 
	LavenderBlue = color.RGBA{R: 0x8b, G: 0x88, B: 0xf8, A:0xff }
	
	// 250 light grass green #9af764 
	LightGrassGreen = color.RGBA{R: 0x9a, G: 0xf7, B: 0x64, A:0xff }
	
	// 251 light mint green #a6fbb2 
	LightMintGreen = color.RGBA{R: 0xa6, G: 0xfb, B: 0xb2, A:0xff }
	
	// 252 sunflower #ffc512 
	Sunflower = color.RGBA{R: 0xff, G: 0xc5, B: 0x12, A:0xff }
	
	// 253 velvet #750851 
	Velvet = color.RGBA{R: 0x75, G: 0x08, B: 0x51, A:0xff }
	
	// 254 brick orange #c14a09 
	BrickOrange = color.RGBA{R: 0xc1, G: 0x4a, B: 0x09, A:0xff }
	
	// 255 lightish red #fe2f4a 
	LightishRed = color.RGBA{R: 0xfe, G: 0x2f, B: 0x4a, A:0xff }
	
	// 256 pure blue #0203e2 
	PureBlue = color.RGBA{R: 0x02, G: 0x03, B: 0xe2, A:0xff }
	
	// 257 twilight blue #0a437a 
	TwilightBlue = color.RGBA{R: 0x0a, G: 0x43, B: 0x7a, A:0xff }
	
	// 258 violet red #a50055 
	VioletRed = color.RGBA{R: 0xa5, G: 0x00, B: 0x55, A:0xff }
	
	// 259 yellowy brown #ae8b0c 
	YellowyBrown = color.RGBA{R: 0xae, G: 0x8b, B: 0x0c, A:0xff }
	
	// 260 carnation #fd798f 
	Carnation = color.RGBA{R: 0xfd, G: 0x79, B: 0x8f, A:0xff }
	
	// 261 muddy yellow #bfac05 
	MuddyYellow = color.RGBA{R: 0xbf, G: 0xac, B: 0x05, A:0xff }
	
	// 262 dark seafoam green #3eaf76 
	DarkSeafoamGreen = color.RGBA{R: 0x3e, G: 0xaf, B: 0x76, A:0xff }
	
	// 263 deep rose #c74767 
	DeepRose = color.RGBA{R: 0xc7, G: 0x47, B: 0x67, A:0xff }
	
	// 264 dusty red #b9484e 
	DustyRed = color.RGBA{R: 0xb9, G: 0x48, B: 0x4e, A:0xff }
	
	// 265 grey/blue #647d8e 
	Grey_Blue = color.RGBA{R: 0x64, G: 0x7d, B: 0x8e, A:0xff }
	
	// 266 lemon lime #bffe28 
	LemonLime = color.RGBA{R: 0xbf, G: 0xfe, B: 0x28, A:0xff }
	
	// 267 purple/pink #d725de 
	Purple_Pink = color.RGBA{R: 0xd7, G: 0x25, B: 0xde, A:0xff }
	
	// 268 brown yellow #b29705 
	BrownYellow = color.RGBA{R: 0xb2, G: 0x97, B: 0x05, A:0xff }
	
	// 269 purple brown #673a3f 
	PurpleBrown = color.RGBA{R: 0x67, G: 0x3a, B: 0x3f, A:0xff }
	
	// 270 wisteria #a87dc2 
	Wisteria = color.RGBA{R: 0xa8, G: 0x7d, B: 0xc2, A:0xff }
	
	// 271 banana yellow #fafe4b 
	BananaYellow = color.RGBA{R: 0xfa, G: 0xfe, B: 0x4b, A:0xff }
	
	// 272 lipstick red #c0022f 
	LipstickRed = color.RGBA{R: 0xc0, G: 0x02, B: 0x2f, A:0xff }
	
	// 273 water blue #0e87cc 
	WaterBlue = color.RGBA{R: 0x0e, G: 0x87, B: 0xcc, A:0xff }
	
	// 274 brown grey #8d8468 
	BrownGrey = color.RGBA{R: 0x8d, G: 0x84, B: 0x68, A:0xff }
	
	// 275 vibrant purple #ad03de 
	VibrantPurple = color.RGBA{R: 0xad, G: 0x03, B: 0xde, A:0xff }
	
	// 276 baby green #8cff9e 
	BabyGreen = color.RGBA{R: 0x8c, G: 0xff, B: 0x9e, A:0xff }
	
	// 277 barf green #94ac02 
	BarfGreen = color.RGBA{R: 0x94, G: 0xac, B: 0x02, A:0xff }
	
	// 278 eggshell blue #c4fff7 
	EggshellBlue = color.RGBA{R: 0xc4, G: 0xff, B: 0xf7, A:0xff }
	
	// 279 sandy yellow #fdee73 
	SandyYellow = color.RGBA{R: 0xfd, G: 0xee, B: 0x73, A:0xff }
	
	// 280 cool green #33b864 
	CoolGreen = color.RGBA{R: 0x33, G: 0xb8, B: 0x64, A:0xff }
	
	// 281 pale #fff9d0 
	Pale = color.RGBA{R: 0xff, G: 0xf9, B: 0xd0, A:0xff }
	
	// 282 blue/grey #758da3 
	Blue_Grey = color.RGBA{R: 0x75, G: 0x8d, B: 0xa3, A:0xff }
	
	// 283 hot magenta #f504c9 
	HotMagenta = color.RGBA{R: 0xf5, G: 0x04, B: 0xc9, A:0xff }
	
	// 284 greyblue #77a1b5 
	Greyblue = color.RGBA{R: 0x77, G: 0xa1, B: 0xb5, A:0xff }
	
	// 285 purpley #8756e4 
	Purpley = color.RGBA{R: 0x87, G: 0x56, B: 0xe4, A:0xff }
	
	// 286 baby shit green #889717 
	BabyShitGreen = color.RGBA{R: 0x88, G: 0x97, B: 0x17, A:0xff }
	
	// 287 brownish pink #c27e79 
	BrownishPink = color.RGBA{R: 0xc2, G: 0x7e, B: 0x79, A:0xff }
	
	// 288 dark aquamarine #017371 
	DarkAquamarine = color.RGBA{R: 0x01, G: 0x73, B: 0x71, A:0xff }
	
	// 289 diarrhea #9f8303 
	Diarrhea = color.RGBA{R: 0x9f, G: 0x83, B: 0x03, A:0xff }
	
	// 290 light mustard #f7d560 
	LightMustard = color.RGBA{R: 0xf7, G: 0xd5, B: 0x60, A:0xff }
	
	// 291 pale sky blue #bdf6fe 
	PaleSkyBlue = color.RGBA{R: 0xbd, G: 0xf6, B: 0xfe, A:0xff }
	
	// 292 turtle green #75b84f 
	TurtleGreen = color.RGBA{R: 0x75, G: 0xb8, B: 0x4f, A:0xff }
	
	// 293 bright olive #9cbb04 
	BrightOlive = color.RGBA{R: 0x9c, G: 0xbb, B: 0x04, A:0xff }
	
	// 294 dark grey blue #29465b 
	DarkGreyBlue = color.RGBA{R: 0x29, G: 0x46, B: 0x5b, A:0xff }
	
	// 295 greeny brown #696006 
	GreenyBrown = color.RGBA{R: 0x69, G: 0x60, B: 0x06, A:0xff }
	
	// 296 lemon green #adf802 
	LemonGreen = color.RGBA{R: 0xad, G: 0xf8, B: 0x02, A:0xff }
	
	// 297 light periwinkle #c1c6fc 
	LightPeriwinkle = color.RGBA{R: 0xc1, G: 0xc6, B: 0xfc, A:0xff }
	
	// 298 seaweed green #35ad6b 
	SeaweedGreen = color.RGBA{R: 0x35, G: 0xad, B: 0x6b, A:0xff }
	
	// 299 sunshine yellow #fffd37 
	SunshineYellow = color.RGBA{R: 0xff, G: 0xfd, B: 0x37, A:0xff }
	
	// 300 ugly purple #a442a0 
	UglyPurple = color.RGBA{R: 0xa4, G: 0x42, B: 0xa0, A:0xff }
	
	// 301 medium pink #f36196 
	MediumPink = color.RGBA{R: 0xf3, G: 0x61, B: 0x96, A:0xff }
	
	// 302 puke brown #947706 
	PukeBrown = color.RGBA{R: 0x94, G: 0x77, B: 0x06, A:0xff }
	
	// 303 very light pink #fff4f2 
	VeryLightPink = color.RGBA{R: 0xff, G: 0xf4, B: 0xf2, A:0xff }
	
	// 304 viridian #1e9167 
	Viridian = color.RGBA{R: 0x1e, G: 0x91, B: 0x67, A:0xff }
	
	// 305 bile #b5c306 
	Bile = color.RGBA{R: 0xb5, G: 0xc3, B: 0x06, A:0xff }
	
	// 306 faded yellow #feff7f 
	FadedYellow = color.RGBA{R: 0xfe, G: 0xff, B: 0x7f, A:0xff }
	
	// 307 very pale green #cffdbc 
	VeryPaleGreen = color.RGBA{R: 0xcf, G: 0xfd, B: 0xbc, A:0xff }
	
	// 308 vibrant green #0add08 
	VibrantGreen = color.RGBA{R: 0x0a, G: 0xdd, B: 0x08, A:0xff }
	
	// 309 bright lime #87fd05 
	BrightLime = color.RGBA{R: 0x87, G: 0xfd, B: 0x05, A:0xff }
	
	// 310 spearmint #1ef876 
	Spearmint = color.RGBA{R: 0x1e, G: 0xf8, B: 0x76, A:0xff }
	
	// 311 light aquamarine #7bfdc7 
	LightAquamarine = color.RGBA{R: 0x7b, G: 0xfd, B: 0xc7, A:0xff }
	
	// 312 light sage #bcecac 
	LightSage = color.RGBA{R: 0xbc, G: 0xec, B: 0xac, A:0xff }
	
	// 313 yellowgreen #bbf90f 
	Yellowgreen = color.RGBA{R: 0xbb, G: 0xf9, B: 0x0f, A:0xff }
	
	// 314 baby poo #ab9004 
	BabyPoo = color.RGBA{R: 0xab, G: 0x90, B: 0x04, A:0xff }
	
	// 315 dark seafoam #1fb57a 
	DarkSeafoam = color.RGBA{R: 0x1f, G: 0xb5, B: 0x7a, A:0xff }
	
	// 316 deep teal #00555a 
	DeepTeal = color.RGBA{R: 0x00, G: 0x55, B: 0x5a, A:0xff }
	
	// 317 heather #a484ac 
	Heather = color.RGBA{R: 0xa4, G: 0x84, B: 0xac, A:0xff }
	
	// 318 rust orange #c45508 
	RustOrange = color.RGBA{R: 0xc4, G: 0x55, B: 0x08, A:0xff }
	
	// 319 dirty blue #3f829d 
	DirtyBlue = color.RGBA{R: 0x3f, G: 0x82, B: 0x9d, A:0xff }
	
	// 320 fern green #548d44 
	FernGreen = color.RGBA{R: 0x54, G: 0x8d, B: 0x44, A:0xff }
	
	// 321 bright lilac #c95efb 
	BrightLilac = color.RGBA{R: 0xc9, G: 0x5e, B: 0xfb, A:0xff }
	
	// 322 weird green #3ae57f 
	WeirdGreen = color.RGBA{R: 0x3a, G: 0xe5, B: 0x7f, A:0xff }
	
	// 323 peacock blue #016795 
	PeacockBlue = color.RGBA{R: 0x01, G: 0x67, B: 0x95, A:0xff }
	
	// 324 avocado green #87a922 
	AvocadoGreen = color.RGBA{R: 0x87, G: 0xa9, B: 0x22, A:0xff }
	
	// 325 faded orange #f0944d 
	FadedOrange = color.RGBA{R: 0xf0, G: 0x94, B: 0x4d, A:0xff }
	
	// 326 grape purple #5d1451 
	GrapePurple = color.RGBA{R: 0x5d, G: 0x14, B: 0x51, A:0xff }
	
	// 327 hot green #25ff29 
	HotGreen = color.RGBA{R: 0x25, G: 0xff, B: 0x29, A:0xff }
	
	// 328 lime yellow #d0fe1d 
	LimeYellow = color.RGBA{R: 0xd0, G: 0xfe, B: 0x1d, A:0xff }
	
	// 329 mango #ffa62b 
	Mango = color.RGBA{R: 0xff, G: 0xa6, B: 0x2b, A:0xff }
	
	// 330 shamrock #01b44c 
	Shamrock = color.RGBA{R: 0x01, G: 0xb4, B: 0x4c, A:0xff }
	
	// 331 bubblegum #ff6cb5 
	Bubblegum = color.RGBA{R: 0xff, G: 0x6c, B: 0xb5, A:0xff }
	
	// 332 purplish brown #6b4247 
	PurplishBrown = color.RGBA{R: 0x6b, G: 0x42, B: 0x47, A:0xff }
	
	// 333 vomit yellow #c7c10c 
	VomitYellow = color.RGBA{R: 0xc7, G: 0xc1, B: 0x0c, A:0xff }
	
	// 334 pale cyan #b7fffa 
	PaleCyan = color.RGBA{R: 0xb7, G: 0xff, B: 0xfa, A:0xff }
	
	// 335 key lime #aeff6e 
	KeyLime = color.RGBA{R: 0xae, G: 0xff, B: 0x6e, A:0xff }
	
	// 336 tomato red #ec2d01 
	TomatoRed = color.RGBA{R: 0xec, G: 0x2d, B: 0x01, A:0xff }
	
	// 337 lightgreen #76ff7b 
	Lightgreen = color.RGBA{R: 0x76, G: 0xff, B: 0x7b, A:0xff }
	
	// 338 merlot #730039 
	Merlot = color.RGBA{R: 0x73, G: 0x00, B: 0x39, A:0xff }
	
	// 339 night blue #040348 
	NightBlue = color.RGBA{R: 0x04, G: 0x03, B: 0x48, A:0xff }
	
	// 340 purpleish pink #df4ec8 
	PurpleishPink = color.RGBA{R: 0xdf, G: 0x4e, B: 0xc8, A:0xff }
	
	// 341 apple #6ecb3c 
	Apple = color.RGBA{R: 0x6e, G: 0xcb, B: 0x3c, A:0xff }
	
	// 342 baby poop green #8f9805 
	BabyPoopGreen = color.RGBA{R: 0x8f, G: 0x98, B: 0x05, A:0xff }
	
	// 343 green apple #5edc1f 
	GreenApple = color.RGBA{R: 0x5e, G: 0xdc, B: 0x1f, A:0xff }
	
	// 344 heliotrope #d94ff5 
	Heliotrope = color.RGBA{R: 0xd9, G: 0x4f, B: 0xf5, A:0xff }
	
	// 345 yellow/green #c8fd3d 
	Yellow_Green = color.RGBA{R: 0xc8, G: 0xfd, B: 0x3d, A:0xff }
	
	// 346 almost black #070d0d 
	AlmostBlack = color.RGBA{R: 0x07, G: 0x0d, B: 0x0d, A:0xff }
	
	// 347 cool blue #4984b8 
	CoolBlue = color.RGBA{R: 0x49, G: 0x84, B: 0xb8, A:0xff }
	
	// 348 leafy green #51b73b 
	LeafyGreen = color.RGBA{R: 0x51, G: 0xb7, B: 0x3b, A:0xff }
	
	// 349 mustard brown #ac7e04 
	MustardBrown = color.RGBA{R: 0xac, G: 0x7e, B: 0x04, A:0xff }
	
	// 350 dusk #4e5481 
	Dusk = color.RGBA{R: 0x4e, G: 0x54, B: 0x81, A:0xff }
	
	// 351 dull brown #876e4b 
	DullBrown = color.RGBA{R: 0x87, G: 0x6e, B: 0x4b, A:0xff }
	
	// 352 frog green #58bc08 
	FrogGreen = color.RGBA{R: 0x58, G: 0xbc, B: 0x08, A:0xff }
	
	// 353 vivid green #2fef10 
	VividGreen = color.RGBA{R: 0x2f, G: 0xef, B: 0x10, A:0xff }
	
	// 354 bright light green #2dfe54 
	BrightLightGreen = color.RGBA{R: 0x2d, G: 0xfe, B: 0x54, A:0xff }
	
	// 355 fluro green #0aff02 
	FluroGreen = color.RGBA{R: 0x0a, G: 0xff, B: 0x02, A:0xff }
	
	// 356 kiwi #9cef43 
	Kiwi = color.RGBA{R: 0x9c, G: 0xef, B: 0x43, A:0xff }
	
	// 357 seaweed #18d17b 
	Seaweed = color.RGBA{R: 0x18, G: 0xd1, B: 0x7b, A:0xff }
	
	// 358 navy green #35530a 
	NavyGreen = color.RGBA{R: 0x35, G: 0x53, B: 0x0a, A:0xff }
	
	// 359 ultramarine blue #1805db 
	UltramarineBlue = color.RGBA{R: 0x18, G: 0x05, B: 0xdb, A:0xff }
	
	// 360 iris #6258c4 
	Iris = color.RGBA{R: 0x62, G: 0x58, B: 0xc4, A:0xff }
	
	// 361 pastel orange #ff964f 
	PastelOrange = color.RGBA{R: 0xff, G: 0x96, B: 0x4f, A:0xff }
	
	// 362 yellowish orange #ffab0f 
	YellowishOrange = color.RGBA{R: 0xff, G: 0xab, B: 0x0f, A:0xff }
	
	// 363 perrywinkle #8f8ce7 
	Perrywinkle = color.RGBA{R: 0x8f, G: 0x8c, B: 0xe7, A:0xff }
	
	// 364 tealish #24bca8 
	Tealish = color.RGBA{R: 0x24, G: 0xbc, B: 0xa8, A:0xff }
	
	// 365 dark plum #3f012c 
	DarkPlum = color.RGBA{R: 0x3f, G: 0x01, B: 0x2c, A:0xff }
	
	// 366 pear #cbf85f 
	Pear = color.RGBA{R: 0xcb, G: 0xf8, B: 0x5f, A:0xff }
	
	// 367 pinkish orange #ff724c 
	PinkishOrange = color.RGBA{R: 0xff, G: 0x72, B: 0x4c, A:0xff }
	
	// 368 midnight purple #280137 
	MidnightPurple = color.RGBA{R: 0x28, G: 0x01, B: 0x37, A:0xff }
	
	// 369 light urple #b36ff6 
	LightUrple = color.RGBA{R: 0xb3, G: 0x6f, B: 0xf6, A:0xff }
	
	// 370 dark mint #48c072 
	DarkMint = color.RGBA{R: 0x48, G: 0xc0, B: 0x72, A:0xff }
	
	// 371 greenish tan #bccb7a 
	GreenishTan = color.RGBA{R: 0xbc, G: 0xcb, B: 0x7a, A:0xff }
	
	// 372 light burgundy #a8415b 
	LightBurgundy = color.RGBA{R: 0xa8, G: 0x41, B: 0x5b, A:0xff }
	
	// 373 turquoise blue #06b1c4 
	TurquoiseBlue = color.RGBA{R: 0x06, G: 0xb1, B: 0xc4, A:0xff }
	
	// 374 ugly pink #cd7584 
	UglyPink = color.RGBA{R: 0xcd, G: 0x75, B: 0x84, A:0xff }
	
	// 375 sandy #f1da7a 
	Sandy = color.RGBA{R: 0xf1, G: 0xda, B: 0x7a, A:0xff }
	
	// 376 electric pink #ff0490 
	ElectricPink = color.RGBA{R: 0xff, G: 0x04, B: 0x90, A:0xff }
	
	// 377 muted purple #805b87 
	MutedPurple = color.RGBA{R: 0x80, G: 0x5b, B: 0x87, A:0xff }
	
	// 378 mid green #50a747 
	MidGreen = color.RGBA{R: 0x50, G: 0xa7, B: 0x47, A:0xff }
	
	// 379 greyish #a8a495 
	Greyish = color.RGBA{R: 0xa8, G: 0xa4, B: 0x95, A:0xff }
	
	// 380 neon yellow #cfff04 
	NeonYellow = color.RGBA{R: 0xcf, G: 0xff, B: 0x04, A:0xff }
	
	// 381 banana #ffff7e 
	Banana = color.RGBA{R: 0xff, G: 0xff, B: 0x7e, A:0xff }
	
	// 382 carnation pink #ff7fa7 
	CarnationPink = color.RGBA{R: 0xff, G: 0x7f, B: 0xa7, A:0xff }
	
	// 383 tomato #ef4026 
	Tomato = color.RGBA{R: 0xef, G: 0x40, B: 0x26, A:0xff }
	
	// 384 sea #3c9992 
	Sea = color.RGBA{R: 0x3c, G: 0x99, B: 0x92, A:0xff }
	
	// 385 muddy brown #886806 
	MuddyBrown = color.RGBA{R: 0x88, G: 0x68, B: 0x06, A:0xff }
	
	// 386 turquoise green #04f489 
	TurquoiseGreen = color.RGBA{R: 0x04, G: 0xf4, B: 0x89, A:0xff }
	
	// 387 buff #fef69e 
	Buff = color.RGBA{R: 0xfe, G: 0xf6, B: 0x9e, A:0xff }
	
	// 388 fawn #cfaf7b 
	Fawn = color.RGBA{R: 0xcf, G: 0xaf, B: 0x7b, A:0xff }
	
	// 389 muted blue #3b719f 
	MutedBlue = color.RGBA{R: 0x3b, G: 0x71, B: 0x9f, A:0xff }
	
	// 390 pale rose #fdc1c5 
	PaleRose = color.RGBA{R: 0xfd, G: 0xc1, B: 0xc5, A:0xff }
	
	// 391 dark mint green #20c073 
	DarkMintGreen = color.RGBA{R: 0x20, G: 0xc0, B: 0x73, A:0xff }
	
	// 392 amethyst #9b5fc0 
	Amethyst = color.RGBA{R: 0x9b, G: 0x5f, B: 0xc0, A:0xff }
	
	// 393 blue/green #0f9b8e 
	Blue_Green = color.RGBA{R: 0x0f, G: 0x9b, B: 0x8e, A:0xff }
	
	// 394 chestnut #742802 
	Chestnut = color.RGBA{R: 0x74, G: 0x28, B: 0x02, A:0xff }
	
	// 395 sick green #9db92c 
	SickGreen = color.RGBA{R: 0x9d, G: 0xb9, B: 0x2c, A:0xff }
	
	// 396 pea #a4bf20 
	Pea = color.RGBA{R: 0xa4, G: 0xbf, B: 0x20, A:0xff }
	
	// 397 rusty orange #cd5909 
	RustyOrange = color.RGBA{R: 0xcd, G: 0x59, B: 0x09, A:0xff }
	
	// 398 stone #ada587 
	Stone = color.RGBA{R: 0xad, G: 0xa5, B: 0x87, A:0xff }
	
	// 399 rose red #be013c 
	RoseRed = color.RGBA{R: 0xbe, G: 0x01, B: 0x3c, A:0xff }
	
	// 400 pale aqua #b8ffeb 
	PaleAqua = color.RGBA{R: 0xb8, G: 0xff, B: 0xeb, A:0xff }
	
	// 401 deep orange #dc4d01 
	DeepOrange = color.RGBA{R: 0xdc, G: 0x4d, B: 0x01, A:0xff }
	
	// 402 earth #a2653e 
	Earth = color.RGBA{R: 0xa2, G: 0x65, B: 0x3e, A:0xff }
	
	// 403 mossy green #638b27 
	MossyGreen = color.RGBA{R: 0x63, G: 0x8b, B: 0x27, A:0xff }
	
	// 404 grassy green #419c03 
	GrassyGreen = color.RGBA{R: 0x41, G: 0x9c, B: 0x03, A:0xff }
	
	// 405 pale lime green #b1ff65 
	PaleLimeGreen = color.RGBA{R: 0xb1, G: 0xff, B: 0x65, A:0xff }
	
	// 406 light grey blue #9dbcd4 
	LightGreyBlue = color.RGBA{R: 0x9d, G: 0xbc, B: 0xd4, A:0xff }
	
	// 407 pale grey #fdfdfe 
	PaleGrey = color.RGBA{R: 0xfd, G: 0xfd, B: 0xfe, A:0xff }
	
	// 408 asparagus #77ab56 
	Asparagus = color.RGBA{R: 0x77, G: 0xab, B: 0x56, A:0xff }
	
	// 409 blueberry #464196 
	Blueberry = color.RGBA{R: 0x46, G: 0x41, B: 0x96, A:0xff }
	
	// 410 purple red #990147 
	PurpleRed = color.RGBA{R: 0x99, G: 0x01, B: 0x47, A:0xff }
	
	// 411 pale lime #befd73 
	PaleLime = color.RGBA{R: 0xbe, G: 0xfd, B: 0x73, A:0xff }
	
	// 412 greenish teal #32bf84 
	GreenishTeal = color.RGBA{R: 0x32, G: 0xbf, B: 0x84, A:0xff }
	
	// 413 caramel #af6f09 
	Caramel = color.RGBA{R: 0xaf, G: 0x6f, B: 0x09, A:0xff }
	
	// 414 deep magenta #a0025c 
	DeepMagenta = color.RGBA{R: 0xa0, G: 0x02, B: 0x5c, A:0xff }
	
	// 415 light peach #ffd8b1 
	LightPeach = color.RGBA{R: 0xff, G: 0xd8, B: 0xb1, A:0xff }
	
	// 416 milk chocolate #7f4e1e 
	MilkChocolate = color.RGBA{R: 0x7f, G: 0x4e, B: 0x1e, A:0xff }
	
	// 417 ocher #bf9b0c 
	Ocher = color.RGBA{R: 0xbf, G: 0x9b, B: 0x0c, A:0xff }
	
	// 418 off green #6ba353 
	OffGreen = color.RGBA{R: 0x6b, G: 0xa3, B: 0x53, A:0xff }
	
	// 419 purply pink #f075e6 
	PurplyPink = color.RGBA{R: 0xf0, G: 0x75, B: 0xe6, A:0xff }
	
	// 420 lightblue #7bc8f6 
	Lightblue = color.RGBA{R: 0x7b, G: 0xc8, B: 0xf6, A:0xff }
	
	// 421 dusky blue #475f94 
	DuskyBlue = color.RGBA{R: 0x47, G: 0x5f, B: 0x94, A:0xff }
	
	// 422 golden #f5bf03 
	Golden = color.RGBA{R: 0xf5, G: 0xbf, B: 0x03, A:0xff }
	
	// 423 light beige #fffeb6 
	LightBeige = color.RGBA{R: 0xff, G: 0xfe, B: 0xb6, A:0xff }
	
	// 424 butter yellow #fffd74 
	ButterYellow = color.RGBA{R: 0xff, G: 0xfd, B: 0x74, A:0xff }
	
	// 425 dusky purple #895b7b 
	DuskyPurple = color.RGBA{R: 0x89, G: 0x5b, B: 0x7b, A:0xff }
	
	// 426 french blue #436bad 
	FrenchBlue = color.RGBA{R: 0x43, G: 0x6b, B: 0xad, A:0xff }
	
	// 427 ugly yellow #d0c101 
	UglyYellow = color.RGBA{R: 0xd0, G: 0xc1, B: 0x01, A:0xff }
	
	// 428 greeny yellow #c6f808 
	GreenyYellow = color.RGBA{R: 0xc6, G: 0xf8, B: 0x08, A:0xff }
	
	// 429 orangish red #f43605 
	OrangishRed = color.RGBA{R: 0xf4, G: 0x36, B: 0x05, A:0xff }
	
	// 430 shamrock green #02c14d 
	ShamrockGreen = color.RGBA{R: 0x02, G: 0xc1, B: 0x4d, A:0xff }
	
	// 431 orangish brown #b25f03 
	OrangishBrown = color.RGBA{R: 0xb2, G: 0x5f, B: 0x03, A:0xff }
	
	// 432 tree green #2a7e19 
	TreeGreen = color.RGBA{R: 0x2a, G: 0x7e, B: 0x19, A:0xff }
	
	// 433 deep violet #490648 
	DeepViolet = color.RGBA{R: 0x49, G: 0x06, B: 0x48, A:0xff }
	
	// 434 gunmetal #536267 
	Gunmetal = color.RGBA{R: 0x53, G: 0x62, B: 0x67, A:0xff }
	
	// 435 blue/purple #5a06ef 
	Blue_Purple = color.RGBA{R: 0x5a, G: 0x06, B: 0xef, A:0xff }
	
	// 436 cherry #cf0234 
	Cherry = color.RGBA{R: 0xcf, G: 0x02, B: 0x34, A:0xff }
	
	// 437 sandy brown #c4a661 
	SandyBrown = color.RGBA{R: 0xc4, G: 0xa6, B: 0x61, A:0xff }
	
	// 438 warm grey #978a84 
	WarmGrey = color.RGBA{R: 0x97, G: 0x8a, B: 0x84, A:0xff }
	
	// 439 dark indigo #1f0954 
	DarkIndigo = color.RGBA{R: 0x1f, G: 0x09, B: 0x54, A:0xff }
	
	// 440 midnight #03012d 
	Midnight = color.RGBA{R: 0x03, G: 0x01, B: 0x2d, A:0xff }
	
	// 441 bluey green #2bb179 
	BlueyGreen = color.RGBA{R: 0x2b, G: 0xb1, B: 0x79, A:0xff }
	
	// 442 grey pink #c3909b 
	GreyPink = color.RGBA{R: 0xc3, G: 0x90, B: 0x9b, A:0xff }
	
	// 443 soft purple #a66fb5 
	SoftPurple = color.RGBA{R: 0xa6, G: 0x6f, B: 0xb5, A:0xff }
	
	// 444 blood #770001 
	Blood = color.RGBA{R: 0x77, G: 0x00, B: 0x01, A:0xff }
	
	// 445 brown red #922b05 
	BrownRed = color.RGBA{R: 0x92, G: 0x2b, B: 0x05, A:0xff }
	
	// 446 medium grey #7d7f7c 
	MediumGrey = color.RGBA{R: 0x7d, G: 0x7f, B: 0x7c, A:0xff }
	
	// 447 berry #990f4b 
	Berry = color.RGBA{R: 0x99, G: 0x0f, B: 0x4b, A:0xff }
	
	// 448 poo #8f7303 
	Poo = color.RGBA{R: 0x8f, G: 0x73, B: 0x03, A:0xff }
	
	// 449 purpley pink #c83cb9 
	PurpleyPink = color.RGBA{R: 0xc8, G: 0x3c, B: 0xb9, A:0xff }
	
	// 450 light salmon #fea993 
	LightSalmon = color.RGBA{R: 0xfe, G: 0xa9, B: 0x93, A:0xff }
	
	// 451 snot #acbb0d 
	Snot = color.RGBA{R: 0xac, G: 0xbb, B: 0x0d, A:0xff }
	
	// 452 easter purple #c071fe 
	EasterPurple = color.RGBA{R: 0xc0, G: 0x71, B: 0xfe, A:0xff }
	
	// 453 light yellow green #ccfd7f 
	LightYellowGreen = color.RGBA{R: 0xcc, G: 0xfd, B: 0x7f, A:0xff }
	
	// 454 dark navy blue #00022e 
	DarkNavyBlue = color.RGBA{R: 0x00, G: 0x02, B: 0x2e, A:0xff }
	
	// 455 drab #828344 
	Drab = color.RGBA{R: 0x82, G: 0x83, B: 0x44, A:0xff }
	
	// 456 light rose #ffc5cb 
	LightRose = color.RGBA{R: 0xff, G: 0xc5, B: 0xcb, A:0xff }
	
	// 457 rouge #ab1239 
	Rouge = color.RGBA{R: 0xab, G: 0x12, B: 0x39, A:0xff }
	
	// 458 purplish red #b0054b 
	PurplishRed = color.RGBA{R: 0xb0, G: 0x05, B: 0x4b, A:0xff }
	
	// 459 slime green #99cc04 
	SlimeGreen = color.RGBA{R: 0x99, G: 0xcc, B: 0x04, A:0xff }
	
	// 460 baby poop #937c00 
	BabyPoop = color.RGBA{R: 0x93, G: 0x7c, B: 0x00, A:0xff }
	
	// 461 irish green #019529 
	IrishGreen = color.RGBA{R: 0x01, G: 0x95, B: 0x29, A:0xff }
	
	// 462 pink/purple #ef1de7 
	Pink_Purple = color.RGBA{R: 0xef, G: 0x1d, B: 0xe7, A:0xff }
	
	// 463 dark navy #000435 
	DarkNavy = color.RGBA{R: 0x00, G: 0x04, B: 0x35, A:0xff }
	
	// 464 greeny blue #42b395 
	GreenyBlue = color.RGBA{R: 0x42, G: 0xb3, B: 0x95, A:0xff }
	
	// 465 light plum #9d5783 
	LightPlum = color.RGBA{R: 0x9d, G: 0x57, B: 0x83, A:0xff }
	
	// 466 pinkish grey #c8aca9 
	PinkishGrey = color.RGBA{R: 0xc8, G: 0xac, B: 0xa9, A:0xff }
	
	// 467 dirty orange #c87606 
	DirtyOrange = color.RGBA{R: 0xc8, G: 0x76, B: 0x06, A:0xff }
	
	// 468 rust red #aa2704 
	RustRed = color.RGBA{R: 0xaa, G: 0x27, B: 0x04, A:0xff }
	
	// 469 pale lilac #e4cbff 
	PaleLilac = color.RGBA{R: 0xe4, G: 0xcb, B: 0xff, A:0xff }
	
	// 470 orangey red #fa4224 
	OrangeyRed = color.RGBA{R: 0xfa, G: 0x42, B: 0x24, A:0xff }
	
	// 471 primary blue #0804f9 
	PrimaryBlue = color.RGBA{R: 0x08, G: 0x04, B: 0xf9, A:0xff }
	
	// 472 kermit green #5cb200 
	KermitGreen = color.RGBA{R: 0x5c, G: 0xb2, B: 0x00, A:0xff }
	
	// 473 brownish purple #76424e 
	BrownishPurple = color.RGBA{R: 0x76, G: 0x42, B: 0x4e, A:0xff }
	
	// 474 murky green #6c7a0e 
	MurkyGreen = color.RGBA{R: 0x6c, G: 0x7a, B: 0x0e, A:0xff }
	
	// 475 wheat #fbdd7e 
	Wheat = color.RGBA{R: 0xfb, G: 0xdd, B: 0x7e, A:0xff }
	
	// 476 very dark purple #2a0134 
	VeryDarkPurple = color.RGBA{R: 0x2a, G: 0x01, B: 0x34, A:0xff }
	
	// 477 bottle green #044a05 
	BottleGreen = color.RGBA{R: 0x04, G: 0x4a, B: 0x05, A:0xff }
	
	// 478 watermelon #fd4659 
	Watermelon = color.RGBA{R: 0xfd, G: 0x46, B: 0x59, A:0xff }
	
	// 479 deep sky blue #0d75f8 
	DeepSkyBlue = color.RGBA{R: 0x0d, G: 0x75, B: 0xf8, A:0xff }
	
	// 480 fire engine red #fe0002 
	FireEngineRed = color.RGBA{R: 0xfe, G: 0x00, B: 0x02, A:0xff }
	
	// 481 yellow ochre #cb9d06 
	YellowOchre = color.RGBA{R: 0xcb, G: 0x9d, B: 0x06, A:0xff }
	
	// 482 pumpkin orange #fb7d07 
	PumpkinOrange = color.RGBA{R: 0xfb, G: 0x7d, B: 0x07, A:0xff }
	
	// 483 pale olive #b9cc81 
	PaleOlive = color.RGBA{R: 0xb9, G: 0xcc, B: 0x81, A:0xff }
	
	// 484 light lilac #edc8ff 
	LightLilac = color.RGBA{R: 0xed, G: 0xc8, B: 0xff, A:0xff }
	
	// 485 lightish green #61e160 
	LightishGreen = color.RGBA{R: 0x61, G: 0xe1, B: 0x60, A:0xff }
	
	// 486 carolina blue #8ab8fe 
	CarolinaBlue = color.RGBA{R: 0x8a, G: 0xb8, B: 0xfe, A:0xff }
	
	// 487 mulberry #920a4e 
	Mulberry = color.RGBA{R: 0x92, G: 0x0a, B: 0x4e, A:0xff }
	
	// 488 shocking pink #fe02a2 
	ShockingPink = color.RGBA{R: 0xfe, G: 0x02, B: 0xa2, A:0xff }
	
	// 489 auburn #9a3001 
	Auburn = color.RGBA{R: 0x9a, G: 0x30, B: 0x01, A:0xff }
	
	// 490 bright lime green #65fe08 
	BrightLimeGreen = color.RGBA{R: 0x65, G: 0xfe, B: 0x08, A:0xff }
	
	// 491 celadon #befdb7 
	Celadon = color.RGBA{R: 0xbe, G: 0xfd, B: 0xb7, A:0xff }
	
	// 492 pinkish brown #b17261 
	PinkishBrown = color.RGBA{R: 0xb1, G: 0x72, B: 0x61, A:0xff }
	
	// 493 poo brown #885f01 
	PooBrown = color.RGBA{R: 0x88, G: 0x5f, B: 0x01, A:0xff }
	
	// 494 bright sky blue #02ccfe 
	BrightSkyBlue = color.RGBA{R: 0x02, G: 0xcc, B: 0xfe, A:0xff }
	
	// 495 celery #c1fd95 
	Celery = color.RGBA{R: 0xc1, G: 0xfd, B: 0x95, A:0xff }
	
	// 496 dirt brown #836539 
	DirtBrown = color.RGBA{R: 0x83, G: 0x65, B: 0x39, A:0xff }
	
	// 497 strawberry #fb2943 
	Strawberry = color.RGBA{R: 0xfb, G: 0x29, B: 0x43, A:0xff }
	
	// 498 dark lime #84b701 
	DarkLime = color.RGBA{R: 0x84, G: 0xb7, B: 0x01, A:0xff }
	
	// 499 copper #b66325 
	Copper = color.RGBA{R: 0xb6, G: 0x63, B: 0x25, A:0xff }
	
	// 500 medium brown #7f5112 
	MediumBrown = color.RGBA{R: 0x7f, G: 0x51, B: 0x12, A:0xff }
	
	// 501 muted green #5fa052 
	MutedGreen = color.RGBA{R: 0x5f, G: 0xa0, B: 0x52, A:0xff }
	
	// 502 robin's egg #6dedfd 
	RobinsEgg = color.RGBA{R: 0x6d, G: 0xed, B: 0xfd, A:0xff }
	
	// 503 bright aqua #0bf9ea 
	BrightAqua = color.RGBA{R: 0x0b, G: 0xf9, B: 0xea, A:0xff }
	
	// 504 bright lavender #c760ff 
	BrightLavender = color.RGBA{R: 0xc7, G: 0x60, B: 0xff, A:0xff }
	
	// 505 ivory #ffffcb 
	Ivory = color.RGBA{R: 0xff, G: 0xff, B: 0xcb, A:0xff }
	
	// 506 very light purple #f6cefc 
	VeryLightPurple = color.RGBA{R: 0xf6, G: 0xce, B: 0xfc, A:0xff }
	
	// 507 light navy #155084 
	LightNavy = color.RGBA{R: 0x15, G: 0x50, B: 0x84, A:0xff }
	
	// 508 pink red #f5054f 
	PinkRed = color.RGBA{R: 0xf5, G: 0x05, B: 0x4f, A:0xff }
	
	// 509 olive brown #645403 
	OliveBrown = color.RGBA{R: 0x64, G: 0x54, B: 0x03, A:0xff }
	
	// 510 poop brown #7a5901 
	PoopBrown = color.RGBA{R: 0x7a, G: 0x59, B: 0x01, A:0xff }
	
	// 511 mustard green #a8b504 
	MustardGreen = color.RGBA{R: 0xa8, G: 0xb5, B: 0x04, A:0xff }
	
	// 512 ocean green #3d9973 
	OceanGreen = color.RGBA{R: 0x3d, G: 0x99, B: 0x73, A:0xff }
	
	// 513 very dark blue #000133 
	VeryDarkBlue = color.RGBA{R: 0x00, G: 0x01, B: 0x33, A:0xff }
	
	// 514 dusty green #76a973 
	DustyGreen = color.RGBA{R: 0x76, G: 0xa9, B: 0x73, A:0xff }
	
	// 515 light navy blue #2e5a88 
	LightNavyBlue = color.RGBA{R: 0x2e, G: 0x5a, B: 0x88, A:0xff }
	
	// 516 minty green #0bf77d 
	MintyGreen = color.RGBA{R: 0x0b, G: 0xf7, B: 0x7d, A:0xff }
	
	// 517 adobe #bd6c48 
	Adobe = color.RGBA{R: 0xbd, G: 0x6c, B: 0x48, A:0xff }
	
	// 518 barney #ac1db8 
	Barney = color.RGBA{R: 0xac, G: 0x1d, B: 0xb8, A:0xff }
	
	// 519 jade green #2baf6a 
	JadeGreen = color.RGBA{R: 0x2b, G: 0xaf, B: 0x6a, A:0xff }
	
	// 520 bright light blue #26f7fd 
	BrightLightBlue = color.RGBA{R: 0x26, G: 0xf7, B: 0xfd, A:0xff }
	
	// 521 light lime #aefd6c 
	LightLime = color.RGBA{R: 0xae, G: 0xfd, B: 0x6c, A:0xff }
	
	// 522 dark khaki #9b8f55 
	DarkKhaki = color.RGBA{R: 0x9b, G: 0x8f, B: 0x55, A:0xff }
	
	// 523 orange yellow #ffad01 
	OrangeYellow = color.RGBA{R: 0xff, G: 0xad, B: 0x01, A:0xff }
	
	// 524 ocre #c69c04 
	Ocre = color.RGBA{R: 0xc6, G: 0x9c, B: 0x04, A:0xff }
	
	// 525 maize #f4d054 
	Maize = color.RGBA{R: 0xf4, G: 0xd0, B: 0x54, A:0xff }
	
	// 526 faded pink #de9dac 
	FadedPink = color.RGBA{R: 0xde, G: 0x9d, B: 0xac, A:0xff }
	
	// 527 british racing green #05480d 
	BritishRacingGreen = color.RGBA{R: 0x05, G: 0x48, B: 0x0d, A:0xff }
	
	// 528 sandstone #c9ae74 
	Sandstone = color.RGBA{R: 0xc9, G: 0xae, B: 0x74, A:0xff }
	
	// 529 mud brown #60460f 
	MudBrown = color.RGBA{R: 0x60, G: 0x46, B: 0x0f, A:0xff }
	
	// 530 light sea green #98f6b0 
	LightSeaGreen = color.RGBA{R: 0x98, G: 0xf6, B: 0xb0, A:0xff }
	
	// 531 robin egg blue #8af1fe 
	RobinEggBlue = color.RGBA{R: 0x8a, G: 0xf1, B: 0xfe, A:0xff }
	
	// 532 aqua marine #2ee8bb 
	AquaMarine = color.RGBA{R: 0x2e, G: 0xe8, B: 0xbb, A:0xff }
	
	// 533 dark sea green #11875d 
	DarkSeaGreen = color.RGBA{R: 0x11, G: 0x87, B: 0x5d, A:0xff }
	
	// 534 soft pink #fdb0c0 
	SoftPink = color.RGBA{R: 0xfd, G: 0xb0, B: 0xc0, A:0xff }
	
	// 535 orangey brown #b16002 
	OrangeyBrown = color.RGBA{R: 0xb1, G: 0x60, B: 0x02, A:0xff }
	
	// 536 cherry red #f7022a 
	CherryRed = color.RGBA{R: 0xf7, G: 0x02, B: 0x2a, A:0xff }
	
	// 537 burnt yellow #d5ab09 
	BurntYellow = color.RGBA{R: 0xd5, G: 0xab, B: 0x09, A:0xff }
	
	// 538 brownish grey #86775f 
	BrownishGrey = color.RGBA{R: 0x86, G: 0x77, B: 0x5f, A:0xff }
	
	// 539 camel #c69f59 
	Camel = color.RGBA{R: 0xc6, G: 0x9f, B: 0x59, A:0xff }
	
	// 540 purplish grey #7a687f 
	PurplishGrey = color.RGBA{R: 0x7a, G: 0x68, B: 0x7f, A:0xff }
	
	// 541 marine #042e60 
	Marine = color.RGBA{R: 0x04, G: 0x2e, B: 0x60, A:0xff }
	
	// 542 greyish pink #c88d94 
	GreyishPink = color.RGBA{R: 0xc8, G: 0x8d, B: 0x94, A:0xff }
	
	// 543 pale turquoise #a5fbd5 
	PaleTurquoise = color.RGBA{R: 0xa5, G: 0xfb, B: 0xd5, A:0xff }
	
	// 544 pastel yellow #fffe71 
	PastelYellow = color.RGBA{R: 0xff, G: 0xfe, B: 0x71, A:0xff }
	
	// 545 bluey purple #6241c7 
	BlueyPurple = color.RGBA{R: 0x62, G: 0x41, B: 0xc7, A:0xff }
	
	// 546 canary yellow #fffe40 
	CanaryYellow = color.RGBA{R: 0xff, G: 0xfe, B: 0x40, A:0xff }
	
	// 547 faded red #d3494e 
	FadedRed = color.RGBA{R: 0xd3, G: 0x49, B: 0x4e, A:0xff }
	
	// 548 sepia #985e2b 
	Sepia = color.RGBA{R: 0x98, G: 0x5e, B: 0x2b, A:0xff }
	
	// 549 coffee #a6814c 
	Coffee = color.RGBA{R: 0xa6, G: 0x81, B: 0x4c, A:0xff }
	
	// 550 bright magenta #ff08e8 
	BrightMagenta = color.RGBA{R: 0xff, G: 0x08, B: 0xe8, A:0xff }
	
	// 551 mocha #9d7651 
	Mocha = color.RGBA{R: 0x9d, G: 0x76, B: 0x51, A:0xff }
	
	// 552 ecru #feffca 
	Ecru = color.RGBA{R: 0xfe, G: 0xff, B: 0xca, A:0xff }
	
	// 553 purpleish #98568d 
	Purpleish = color.RGBA{R: 0x98, G: 0x56, B: 0x8d, A:0xff }
	
	// 554 cranberry #9e003a 
	Cranberry = color.RGBA{R: 0x9e, G: 0x00, B: 0x3a, A:0xff }
	
	// 555 darkish green #287c37 
	DarkishGreen = color.RGBA{R: 0x28, G: 0x7c, B: 0x37, A:0xff }
	
	// 556 brown orange #b96902 
	BrownOrange = color.RGBA{R: 0xb9, G: 0x69, B: 0x02, A:0xff }
	
	// 557 dusky rose #ba6873 
	DuskyRose = color.RGBA{R: 0xba, G: 0x68, B: 0x73, A:0xff }
	
	// 558 melon #ff7855 
	Melon = color.RGBA{R: 0xff, G: 0x78, B: 0x55, A:0xff }
	
	// 559 sickly green #94b21c 
	SicklyGreen = color.RGBA{R: 0x94, G: 0xb2, B: 0x1c, A:0xff }
	
	// 560 silver #c5c9c7 
	Silver = color.RGBA{R: 0xc5, G: 0xc9, B: 0xc7, A:0xff }
	
	// 561 purply blue #661aee 
	PurplyBlue = color.RGBA{R: 0x66, G: 0x1a, B: 0xee, A:0xff }
	
	// 562 purpleish blue #6140ef 
	PurpleishBlue = color.RGBA{R: 0x61, G: 0x40, B: 0xef, A:0xff }
	
	// 563 hospital green #9be5aa 
	HospitalGreen = color.RGBA{R: 0x9b, G: 0xe5, B: 0xaa, A:0xff }
	
	// 564 shit brown #7b5804 
	ShitBrown = color.RGBA{R: 0x7b, G: 0x58, B: 0x04, A:0xff }
	
	// 565 mid blue #276ab3 
	MidBlue = color.RGBA{R: 0x27, G: 0x6a, B: 0xb3, A:0xff }
	
	// 566 amber #feb308 
	Amber = color.RGBA{R: 0xfe, G: 0xb3, B: 0x08, A:0xff }
	
	// 567 easter green #8cfd7e 
	EasterGreen = color.RGBA{R: 0x8c, G: 0xfd, B: 0x7e, A:0xff }
	
	// 568 soft blue #6488ea 
	SoftBlue = color.RGBA{R: 0x64, G: 0x88, B: 0xea, A:0xff }
	
	// 569 cerulean blue #056eee 
	CeruleanBlue = color.RGBA{R: 0x05, G: 0x6e, B: 0xee, A:0xff }
	
	// 570 golden brown #b27a01 
	GoldenBrown = color.RGBA{R: 0xb2, G: 0x7a, B: 0x01, A:0xff }
	
	// 571 bright turquoise #0ffef9 
	BrightTurquoise = color.RGBA{R: 0x0f, G: 0xfe, B: 0xf9, A:0xff }
	
	// 572 red pink #fa2a55 
	RedPink = color.RGBA{R: 0xfa, G: 0x2a, B: 0x55, A:0xff }
	
	// 573 red purple #820747 
	RedPurple = color.RGBA{R: 0x82, G: 0x07, B: 0x47, A:0xff }
	
	// 574 greyish brown #7a6a4f 
	GreyishBrown = color.RGBA{R: 0x7a, G: 0x6a, B: 0x4f, A:0xff }
	
	// 575 vermillion #f4320c 
	Vermillion = color.RGBA{R: 0xf4, G: 0x32, B: 0x0c, A:0xff }
	
	// 576 russet #a13905 
	Russet = color.RGBA{R: 0xa1, G: 0x39, B: 0x05, A:0xff }
	
	// 577 steel grey #6f828a 
	SteelGrey = color.RGBA{R: 0x6f, G: 0x82, B: 0x8a, A:0xff }
	
	// 578 lighter purple #a55af4 
	LighterPurple = color.RGBA{R: 0xa5, G: 0x5a, B: 0xf4, A:0xff }
	
	// 579 bright violet #ad0afd 
	BrightViolet = color.RGBA{R: 0xad, G: 0x0a, B: 0xfd, A:0xff }
	
	// 580 prussian blue #004577 
	PrussianBlue = color.RGBA{R: 0x00, G: 0x45, B: 0x77, A:0xff }
	
	// 581 slate green #658d6d 
	SlateGreen = color.RGBA{R: 0x65, G: 0x8d, B: 0x6d, A:0xff }
	
	// 582 dirty pink #ca7b80 
	DirtyPink = color.RGBA{R: 0xca, G: 0x7b, B: 0x80, A:0xff }
	
	// 583 dark blue green #005249 
	DarkBlueGreen = color.RGBA{R: 0x00, G: 0x52, B: 0x49, A:0xff }
	
	// 584 pine #2b5d34 
	Pine = color.RGBA{R: 0x2b, G: 0x5d, B: 0x34, A:0xff }
	
	// 585 yellowy green #bff128 
	YellowyGreen = color.RGBA{R: 0xbf, G: 0xf1, B: 0x28, A:0xff }
	
	// 586 dark gold #b59410 
	DarkGold = color.RGBA{R: 0xb5, G: 0x94, B: 0x10, A:0xff }
	
	// 587 bluish #2976bb 
	Bluish = color.RGBA{R: 0x29, G: 0x76, B: 0xbb, A:0xff }
	
	// 588 darkish blue #014182 
	DarkishBlue = color.RGBA{R: 0x01, G: 0x41, B: 0x82, A:0xff }
	
	// 589 dull red #bb3f3f 
	DullRed = color.RGBA{R: 0xbb, G: 0x3f, B: 0x3f, A:0xff }
	
	// 590 pinky red #fc2647 
	PinkyRed = color.RGBA{R: 0xfc, G: 0x26, B: 0x47, A:0xff }
	
	// 591 bronze #a87900 
	Bronze = color.RGBA{R: 0xa8, G: 0x79, B: 0x00, A:0xff }
	
	// 592 pale teal #82cbb2 
	PaleTeal = color.RGBA{R: 0x82, G: 0xcb, B: 0xb2, A:0xff }
	
	// 593 military green #667c3e 
	MilitaryGreen = color.RGBA{R: 0x66, G: 0x7c, B: 0x3e, A:0xff }
	
	// 594 barbie pink #fe46a5 
	BarbiePink = color.RGBA{R: 0xfe, G: 0x46, B: 0xa5, A:0xff }
	
	// 595 bubblegum pink #fe83cc 
	BubblegumPink = color.RGBA{R: 0xfe, G: 0x83, B: 0xcc, A:0xff }
	
	// 596 pea soup green #94a617 
	PeaSoupGreen = color.RGBA{R: 0x94, G: 0xa6, B: 0x17, A:0xff }
	
	// 597 dark mustard #a88905 
	DarkMustard = color.RGBA{R: 0xa8, G: 0x89, B: 0x05, A:0xff }
	
	// 598 shit #7f5f00 
	Shit = color.RGBA{R: 0x7f, G: 0x5f, B: 0x00, A:0xff }
	
	// 599 medium purple #9e43a2 
	MediumPurple = color.RGBA{R: 0x9e, G: 0x43, B: 0xa2, A:0xff }
	
	// 600 very dark green #062e03 
	VeryDarkGreen = color.RGBA{R: 0x06, G: 0x2e, B: 0x03, A:0xff }
	
	// 601 dirt #8a6e45 
	Dirt = color.RGBA{R: 0x8a, G: 0x6e, B: 0x45, A:0xff }
	
	// 602 dusky pink #cc7a8b 
	DuskyPink = color.RGBA{R: 0xcc, G: 0x7a, B: 0x8b, A:0xff }
	
	// 603 red violet #9e0168 
	RedViolet = color.RGBA{R: 0x9e, G: 0x01, B: 0x68, A:0xff }
	
	// 604 lemon yellow #fdff38 
	LemonYellow = color.RGBA{R: 0xfd, G: 0xff, B: 0x38, A:0xff }
	
	// 605 pistachio #c0fa8b 
	Pistachio = color.RGBA{R: 0xc0, G: 0xfa, B: 0x8b, A:0xff }
	
	// 606 dull yellow #eedc5b 
	DullYellow = color.RGBA{R: 0xee, G: 0xdc, B: 0x5b, A:0xff }
	
	// 607 dark lime green #7ebd01 
	DarkLimeGreen = color.RGBA{R: 0x7e, G: 0xbd, B: 0x01, A:0xff }
	
	// 608 denim blue #3b5b92 
	DenimBlue = color.RGBA{R: 0x3b, G: 0x5b, B: 0x92, A:0xff }
	
	// 609 teal blue #01889f 
	TealBlue = color.RGBA{R: 0x01, G: 0x88, B: 0x9f, A:0xff }
	
	// 610 lightish blue #3d7afd 
	LightishBlue = color.RGBA{R: 0x3d, G: 0x7a, B: 0xfd, A:0xff }
	
	// 611 purpley blue #5f34e7 
	PurpleyBlue = color.RGBA{R: 0x5f, G: 0x34, B: 0xe7, A:0xff }
	
	// 612 light indigo #6d5acf 
	LightIndigo = color.RGBA{R: 0x6d, G: 0x5a, B: 0xcf, A:0xff }
	
	// 613 swamp green #748500 
	SwampGreen = color.RGBA{R: 0x74, G: 0x85, B: 0x00, A:0xff }
	
	// 614 brown green #706c11 
	BrownGreen = color.RGBA{R: 0x70, G: 0x6c, B: 0x11, A:0xff }
	
	// 615 dark maroon #3c0008 
	DarkMaroon = color.RGBA{R: 0x3c, G: 0x00, B: 0x08, A:0xff }
	
	// 616 hot purple #cb00f5 
	HotPurple = color.RGBA{R: 0xcb, G: 0x00, B: 0xf5, A:0xff }
	
	// 617 dark forest green #002d04 
	DarkForestGreen = color.RGBA{R: 0x00, G: 0x2d, B: 0x04, A:0xff }
	
	// 618 faded blue #658cbb 
	FadedBlue = color.RGBA{R: 0x65, G: 0x8c, B: 0xbb, A:0xff }
	
	// 619 drab green #749551 
	DrabGreen = color.RGBA{R: 0x74, G: 0x95, B: 0x51, A:0xff }
	
	// 620 light lime green #b9ff66 
	LightLimeGreen = color.RGBA{R: 0xb9, G: 0xff, B: 0x66, A:0xff }
	
	// 621 snot green #9dc100 
	SnotGreen = color.RGBA{R: 0x9d, G: 0xc1, B: 0x00, A:0xff }
	
	// 622 yellowish #faee66 
	Yellowish = color.RGBA{R: 0xfa, G: 0xee, B: 0x66, A:0xff }
	
	// 623 light blue green #7efbb3 
	LightBlueGreen = color.RGBA{R: 0x7e, G: 0xfb, B: 0xb3, A:0xff }
	
	// 624 bordeaux #7b002c 
	Bordeaux = color.RGBA{R: 0x7b, G: 0x00, B: 0x2c, A:0xff }
	
	// 625 light mauve #c292a1 
	LightMauve = color.RGBA{R: 0xc2, G: 0x92, B: 0xa1, A:0xff }
	
	// 626 ocean #017b92 
	Ocean = color.RGBA{R: 0x01, G: 0x7b, B: 0x92, A:0xff }
	
	// 627 marigold #fcc006 
	Marigold = color.RGBA{R: 0xfc, G: 0xc0, B: 0x06, A:0xff }
	
	// 628 muddy green #657432 
	MuddyGreen = color.RGBA{R: 0x65, G: 0x74, B: 0x32, A:0xff }
	
	// 629 dull orange #d8863b 
	DullOrange = color.RGBA{R: 0xd8, G: 0x86, B: 0x3b, A:0xff }
	
	// 630 steel #738595 
	Steel = color.RGBA{R: 0x73, G: 0x85, B: 0x95, A:0xff }
	
	// 631 electric purple #aa23ff 
	ElectricPurple = color.RGBA{R: 0xaa, G: 0x23, B: 0xff, A:0xff }
	
	// 632 fluorescent green #08ff08 
	FluorescentGreen = color.RGBA{R: 0x08, G: 0xff, B: 0x08, A:0xff }
	
	// 633 yellowish brown #9b7a01 
	YellowishBrown = color.RGBA{R: 0x9b, G: 0x7a, B: 0x01, A:0xff }
	
	// 634 blush #f29e8e 
	Blush = color.RGBA{R: 0xf2, G: 0x9e, B: 0x8e, A:0xff }
	
	// 635 soft green #6fc276 
	SoftGreen = color.RGBA{R: 0x6f, G: 0xc2, B: 0x76, A:0xff }
	
	// 636 bright orange #ff5b00 
	BrightOrange = color.RGBA{R: 0xff, G: 0x5b, B: 0x00, A:0xff }
	
	// 637 lemon #fdff52 
	Lemon = color.RGBA{R: 0xfd, G: 0xff, B: 0x52, A:0xff }
	
	// 638 purple grey #866f85 
	PurpleGrey = color.RGBA{R: 0x86, G: 0x6f, B: 0x85, A:0xff }
	
	// 639 acid green #8ffe09 
	AcidGreen = color.RGBA{R: 0x8f, G: 0xfe, B: 0x09, A:0xff }
	
	// 640 pale lavender #eecffe 
	PaleLavender = color.RGBA{R: 0xee, G: 0xcf, B: 0xfe, A:0xff }
	
	// 641 violet blue #510ac9 
	VioletBlue = color.RGBA{R: 0x51, G: 0x0a, B: 0xc9, A:0xff }
	
	// 642 light forest green #4f9153 
	LightForestGreen = color.RGBA{R: 0x4f, G: 0x91, B: 0x53, A:0xff }
	
	// 643 burnt red #9f2305 
	BurntRed = color.RGBA{R: 0x9f, G: 0x23, B: 0x05, A:0xff }
	
	// 644 khaki green #728639 
	KhakiGreen = color.RGBA{R: 0x72, G: 0x86, B: 0x39, A:0xff }
	
	// 645 cerise #de0c62 
	Cerise = color.RGBA{R: 0xde, G: 0x0c, B: 0x62, A:0xff }
	
	// 646 faded purple #916e99 
	FadedPurple = color.RGBA{R: 0x91, G: 0x6e, B: 0x99, A:0xff }
	
	// 647 apricot #ffb16d 
	Apricot = color.RGBA{R: 0xff, G: 0xb1, B: 0x6d, A:0xff }
	
	// 648 dark olive green #3c4d03 
	DarkOliveGreen = color.RGBA{R: 0x3c, G: 0x4d, B: 0x03, A:0xff }
	
	// 649 grey brown #7f7053 
	GreyBrown = color.RGBA{R: 0x7f, G: 0x70, B: 0x53, A:0xff }
	
	// 650 green grey #77926f 
	GreenGrey = color.RGBA{R: 0x77, G: 0x92, B: 0x6f, A:0xff }
	
	// 651 true blue #010fcc 
	TrueBlue = color.RGBA{R: 0x01, G: 0x0f, B: 0xcc, A:0xff }
	
	// 652 pale violet #ceaefa 
	PaleViolet = color.RGBA{R: 0xce, G: 0xae, B: 0xfa, A:0xff }
	
	// 653 periwinkle blue #8f99fb 
	PeriwinkleBlue = color.RGBA{R: 0x8f, G: 0x99, B: 0xfb, A:0xff }
	
	// 654 light sky blue #c6fcff 
	LightSkyBlue = color.RGBA{R: 0xc6, G: 0xfc, B: 0xff, A:0xff }
	
	// 655 blurple #5539cc 
	Blurple = color.RGBA{R: 0x55, G: 0x39, B: 0xcc, A:0xff }
	
	// 656 green brown #544e03 
	GreenBrown = color.RGBA{R: 0x54, G: 0x4e, B: 0x03, A:0xff }
	
	// 657 bluegreen #017a79 
	Bluegreen = color.RGBA{R: 0x01, G: 0x7a, B: 0x79, A:0xff }
	
	// 658 bright teal #01f9c6 
	BrightTeal = color.RGBA{R: 0x01, G: 0xf9, B: 0xc6, A:0xff }
	
	// 659 brownish yellow #c9b003 
	BrownishYellow = color.RGBA{R: 0xc9, G: 0xb0, B: 0x03, A:0xff }
	
	// 660 pea soup #929901 
	PeaSoup = color.RGBA{R: 0x92, G: 0x99, B: 0x01, A:0xff }
	
	// 661 forest #0b5509 
	Forest = color.RGBA{R: 0x0b, G: 0x55, B: 0x09, A:0xff }
	
	// 662 barney purple #a00498 
	BarneyPurple = color.RGBA{R: 0xa0, G: 0x04, B: 0x98, A:0xff }
	
	// 663 ultramarine #2000b1 
	Ultramarine = color.RGBA{R: 0x20, G: 0x00, B: 0xb1, A:0xff }
	
	// 664 purplish #94568c 
	Purplish = color.RGBA{R: 0x94, G: 0x56, B: 0x8c, A:0xff }
	
	// 665 puke yellow #c2be0e 
	PukeYellow = color.RGBA{R: 0xc2, G: 0xbe, B: 0x0e, A:0xff }
	
	// 666 bluish grey #748b97 
	BluishGrey = color.RGBA{R: 0x74, G: 0x8b, B: 0x97, A:0xff }
	
	// 667 dark periwinkle #665fd1 
	DarkPeriwinkle = color.RGBA{R: 0x66, G: 0x5f, B: 0xd1, A:0xff }
	
	// 668 dark lilac #9c6da5 
	DarkLilac = color.RGBA{R: 0x9c, G: 0x6d, B: 0xa5, A:0xff }
	
	// 669 reddish #c44240 
	Reddish = color.RGBA{R: 0xc4, G: 0x42, B: 0x40, A:0xff }
	
	// 670 light maroon #a24857 
	LightMaroon = color.RGBA{R: 0xa2, G: 0x48, B: 0x57, A:0xff }
	
	// 671 dusty purple #825f87 
	DustyPurple = color.RGBA{R: 0x82, G: 0x5f, B: 0x87, A:0xff }
	
	// 672 terra cotta #c9643b 
	TerraCotta = color.RGBA{R: 0xc9, G: 0x64, B: 0x3b, A:0xff }
	
	// 673 avocado #90b134 
	Avocado = color.RGBA{R: 0x90, G: 0xb1, B: 0x34, A:0xff }
	
	// 674 marine blue #01386a 
	MarineBlue = color.RGBA{R: 0x01, G: 0x38, B: 0x6a, A:0xff }
	
	// 675 teal green #25a36f 
	TealGreen = color.RGBA{R: 0x25, G: 0xa3, B: 0x6f, A:0xff }
	
	// 676 slate grey #59656d 
	SlateGrey = color.RGBA{R: 0x59, G: 0x65, B: 0x6d, A:0xff }
	
	// 677 lighter green #75fd63 
	LighterGreen = color.RGBA{R: 0x75, G: 0xfd, B: 0x63, A:0xff }
	
	// 678 electric green #21fc0d 
	ElectricGreen = color.RGBA{R: 0x21, G: 0xfc, B: 0x0d, A:0xff }
	
	// 679 dusty blue #5a86ad 
	DustyBlue = color.RGBA{R: 0x5a, G: 0x86, B: 0xad, A:0xff }
	
	// 680 golden yellow #fec615 
	GoldenYellow = color.RGBA{R: 0xfe, G: 0xc6, B: 0x15, A:0xff }
	
	// 681 bright yellow #fffd01 
	BrightYellow = color.RGBA{R: 0xff, G: 0xfd, B: 0x01, A:0xff }
	
	// 682 light lavender #dfc5fe 
	LightLavender = color.RGBA{R: 0xdf, G: 0xc5, B: 0xfe, A:0xff }
	
	// 683 umber #b26400 
	Umber = color.RGBA{R: 0xb2, G: 0x64, B: 0x00, A:0xff }
	
	// 684 poop #7f5e00 
	Poop = color.RGBA{R: 0x7f, G: 0x5e, B: 0x00, A:0xff }
	
	// 685 dark peach #de7e5d 
	DarkPeach = color.RGBA{R: 0xde, G: 0x7e, B: 0x5d, A:0xff }
	
	// 686 jungle green #048243 
	JungleGreen = color.RGBA{R: 0x04, G: 0x82, B: 0x43, A:0xff }
	
	// 687 eggshell #ffffd4 
	Eggshell = color.RGBA{R: 0xff, G: 0xff, B: 0xd4, A:0xff }
	
	// 688 denim #3b638c 
	Denim = color.RGBA{R: 0x3b, G: 0x63, B: 0x8c, A:0xff }
	
	// 689 yellow brown #b79400 
	YellowBrown = color.RGBA{R: 0xb7, G: 0x94, B: 0x00, A:0xff }
	
	// 690 dull purple #84597e 
	DullPurple = color.RGBA{R: 0x84, G: 0x59, B: 0x7e, A:0xff }
	
	// 691 chocolate brown #411900 
	ChocolateBrown = color.RGBA{R: 0x41, G: 0x19, B: 0x00, A:0xff }
	
	// 692 wine red #7b0323 
	WineRed = color.RGBA{R: 0x7b, G: 0x03, B: 0x23, A:0xff }
	
	// 693 neon blue #04d9ff 
	NeonBlue = color.RGBA{R: 0x04, G: 0xd9, B: 0xff, A:0xff }
	
	// 694 dirty green #667e2c 
	DirtyGreen = color.RGBA{R: 0x66, G: 0x7e, B: 0x2c, A:0xff }
	
	// 695 light tan #fbeeac 
	LightTan = color.RGBA{R: 0xfb, G: 0xee, B: 0xac, A:0xff }
	
	// 696 ice blue #d7fffe 
	IceBlue = color.RGBA{R: 0xd7, G: 0xff, B: 0xfe, A:0xff }
	
	// 697 cadet blue #4e7496 
	CadetBlue = color.RGBA{R: 0x4e, G: 0x74, B: 0x96, A:0xff }
	
	// 698 dark mauve #874c62 
	DarkMauve = color.RGBA{R: 0x87, G: 0x4c, B: 0x62, A:0xff }
	
	// 699 very light blue #d5ffff 
	VeryLightBlue = color.RGBA{R: 0xd5, G: 0xff, B: 0xff, A:0xff }
	
	// 700 grey purple #826d8c 
	GreyPurple = color.RGBA{R: 0x82, G: 0x6d, B: 0x8c, A:0xff }
	
	// 701 pastel pink #ffbacd 
	PastelPink = color.RGBA{R: 0xff, G: 0xba, B: 0xcd, A:0xff }
	
	// 702 very light green #d1ffbd 
	VeryLightGreen = color.RGBA{R: 0xd1, G: 0xff, B: 0xbd, A:0xff }
	
	// 703 dark sky blue #448ee4 
	DarkSkyBlue = color.RGBA{R: 0x44, G: 0x8e, B: 0xe4, A:0xff }
	
	// 704 evergreen #05472a 
	Evergreen = color.RGBA{R: 0x05, G: 0x47, B: 0x2a, A:0xff }
	
	// 705 dull pink #d5869d 
	DullPink = color.RGBA{R: 0xd5, G: 0x86, B: 0x9d, A:0xff }
	
	// 706 aubergine #3d0734 
	Aubergine = color.RGBA{R: 0x3d, G: 0x07, B: 0x34, A:0xff }
	
	// 707 mahogany #4a0100 
	Mahogany = color.RGBA{R: 0x4a, G: 0x01, B: 0x00, A:0xff }
	
	// 708 reddish orange #f8481c 
	ReddishOrange = color.RGBA{R: 0xf8, G: 0x48, B: 0x1c, A:0xff }
	
	// 709 deep green #02590f 
	DeepGreen = color.RGBA{R: 0x02, G: 0x59, B: 0x0f, A:0xff }
	
	// 710 vomit green #89a203 
	VomitGreen = color.RGBA{R: 0x89, G: 0xa2, B: 0x03, A:0xff }
	
	// 711 purple pink #e03fd8 
	PurplePink = color.RGBA{R: 0xe0, G: 0x3f, B: 0xd8, A:0xff }
	
	// 712 dusty pink #d58a94 
	DustyPink = color.RGBA{R: 0xd5, G: 0x8a, B: 0x94, A:0xff }
	
	// 713 faded green #7bb274 
	FadedGreen = color.RGBA{R: 0x7b, G: 0xb2, B: 0x74, A:0xff }
	
	// 714 camo green #526525 
	CamoGreen = color.RGBA{R: 0x52, G: 0x65, B: 0x25, A:0xff }
	
	// 715 pinky purple #c94cbe 
	PinkyPurple = color.RGBA{R: 0xc9, G: 0x4c, B: 0xbe, A:0xff }
	
	// 716 pink purple #db4bda 
	PinkPurple = color.RGBA{R: 0xdb, G: 0x4b, B: 0xda, A:0xff }
	
	// 717 brownish red #9e3623 
	BrownishRed = color.RGBA{R: 0x9e, G: 0x36, B: 0x23, A:0xff }
	
	// 718 dark rose #b5485d 
	DarkRose = color.RGBA{R: 0xb5, G: 0x48, B: 0x5d, A:0xff }
	
	// 719 mud #735c12 
	Mud = color.RGBA{R: 0x73, G: 0x5c, B: 0x12, A:0xff }
	
	// 720 brownish #9c6d57 
	Brownish = color.RGBA{R: 0x9c, G: 0x6d, B: 0x57, A:0xff }
	
	// 721 emerald green #028f1e 
	EmeraldGreen = color.RGBA{R: 0x02, G: 0x8f, B: 0x1e, A:0xff }
	
	// 722 pale brown #b1916e 
	PaleBrown = color.RGBA{R: 0xb1, G: 0x91, B: 0x6e, A:0xff }
	
	// 723 dull blue #49759c 
	DullBlue = color.RGBA{R: 0x49, G: 0x75, B: 0x9c, A:0xff }
	
	// 724 burnt umber #a0450e 
	BurntUmber = color.RGBA{R: 0xa0, G: 0x45, B: 0x0e, A:0xff }
	
	// 725 medium green #39ad48 
	MediumGreen = color.RGBA{R: 0x39, G: 0xad, B: 0x48, A:0xff }
	
	// 726 clay #b66a50 
	Clay = color.RGBA{R: 0xb6, G: 0x6a, B: 0x50, A:0xff }
	
	// 727 light aqua #8cffdb 
	LightAqua = color.RGBA{R: 0x8c, G: 0xff, B: 0xdb, A:0xff }
	
	// 728 light olive green #a4be5c 
	LightOliveGreen = color.RGBA{R: 0xa4, G: 0xbe, B: 0x5c, A:0xff }
	
	// 729 brownish orange #cb7723 
	BrownishOrange = color.RGBA{R: 0xcb, G: 0x77, B: 0x23, A:0xff }
	
	// 730 dark aqua #05696b 
	DarkAqua = color.RGBA{R: 0x05, G: 0x69, B: 0x6b, A:0xff }
	
	// 731 purplish pink #ce5dae 
	PurplishPink = color.RGBA{R: 0xce, G: 0x5d, B: 0xae, A:0xff }
	
	// 732 dark salmon #c85a53 
	DarkSalmon = color.RGBA{R: 0xc8, G: 0x5a, B: 0x53, A:0xff }
	
	// 733 greenish grey #96ae8d 
	GreenishGrey = color.RGBA{R: 0x96, G: 0xae, B: 0x8d, A:0xff }
	
	// 734 jade #1fa774 
	Jade = color.RGBA{R: 0x1f, G: 0xa7, B: 0x74, A:0xff }
	
	// 735 ugly green #7a9703 
	UglyGreen = color.RGBA{R: 0x7a, G: 0x97, B: 0x03, A:0xff }
	
	// 736 dark beige #ac9362 
	DarkBeige = color.RGBA{R: 0xac, G: 0x93, B: 0x62, A:0xff }
	
	// 737 emerald #01a049 
	Emerald = color.RGBA{R: 0x01, G: 0xa0, B: 0x49, A:0xff }
	
	// 738 pale red #d9544d 
	PaleRed = color.RGBA{R: 0xd9, G: 0x54, B: 0x4d, A:0xff }
	
	// 739 light magenta #fa5ff7 
	LightMagenta = color.RGBA{R: 0xfa, G: 0x5f, B: 0xf7, A:0xff }
	
	// 740 sky #82cafc 
	Sky = color.RGBA{R: 0x82, G: 0xca, B: 0xfc, A:0xff }
	
	// 741 light cyan #acfffc 
	LightCyan = color.RGBA{R: 0xac, G: 0xff, B: 0xfc, A:0xff }
	
	// 742 yellow orange #fcb001 
	YellowOrange = color.RGBA{R: 0xfc, G: 0xb0, B: 0x01, A:0xff }
	
	// 743 reddish purple #910951 
	ReddishPurple = color.RGBA{R: 0x91, G: 0x09, B: 0x51, A:0xff }
	
	// 744 reddish pink #fe2c54 
	ReddishPink = color.RGBA{R: 0xfe, G: 0x2c, B: 0x54, A:0xff }
	
	// 745 orchid #c875c4 
	Orchid = color.RGBA{R: 0xc8, G: 0x75, B: 0xc4, A:0xff }
	
	// 746 dirty yellow #cdc50a 
	DirtyYellow = color.RGBA{R: 0xcd, G: 0xc5, B: 0x0a, A:0xff }
	
	// 747 orange red #fd411e 
	OrangeRed = color.RGBA{R: 0xfd, G: 0x41, B: 0x1e, A:0xff }
	
	// 748 deep red #9a0200 
	DeepRed = color.RGBA{R: 0x9a, G: 0x02, B: 0x00, A:0xff }
	
	// 749 orange brown #be6400 
	OrangeBrown = color.RGBA{R: 0xbe, G: 0x64, B: 0x00, A:0xff }
	
	// 750 cobalt blue #030aa7 
	CobaltBlue = color.RGBA{R: 0x03, G: 0x0a, B: 0xa7, A:0xff }
	
	// 751 neon pink #fe019a 
	NeonPink = color.RGBA{R: 0xfe, G: 0x01, B: 0x9a, A:0xff }
	
	// 752 rose pink #f7879a 
	RosePink = color.RGBA{R: 0xf7, G: 0x87, B: 0x9a, A:0xff }
	
	// 753 greyish purple #887191 
	GreyishPurple = color.RGBA{R: 0x88, G: 0x71, B: 0x91, A:0xff }
	
	// 754 raspberry #b00149 
	Raspberry = color.RGBA{R: 0xb0, G: 0x01, B: 0x49, A:0xff }
	
	// 755 aqua green #12e193 
	AquaGreen = color.RGBA{R: 0x12, G: 0xe1, B: 0x93, A:0xff }
	
	// 756 salmon pink #fe7b7c 
	SalmonPink = color.RGBA{R: 0xfe, G: 0x7b, B: 0x7c, A:0xff }
	
	// 757 tangerine #ff9408 
	Tangerine = color.RGBA{R: 0xff, G: 0x94, B: 0x08, A:0xff }
	
	// 758 brownish green #6a6e09 
	BrownishGreen = color.RGBA{R: 0x6a, G: 0x6e, B: 0x09, A:0xff }
	
	// 759 red brown #8b2e16 
	RedBrown = color.RGBA{R: 0x8b, G: 0x2e, B: 0x16, A:0xff }
	
	// 760 greenish brown #696112 
	GreenishBrown = color.RGBA{R: 0x69, G: 0x61, B: 0x12, A:0xff }
	
	// 761 pumpkin #e17701 
	Pumpkin = color.RGBA{R: 0xe1, G: 0x77, B: 0x01, A:0xff }
	
	// 762 pine green #0a481e 
	PineGreen = color.RGBA{R: 0x0a, G: 0x48, B: 0x1e, A:0xff }
	
	// 763 charcoal #343837 
	Charcoal = color.RGBA{R: 0x34, G: 0x38, B: 0x37, A:0xff }
	
	// 764 baby pink #ffb7ce 
	BabyPink = color.RGBA{R: 0xff, G: 0xb7, B: 0xce, A:0xff }
	
	// 765 cornflower #6a79f7 
	Cornflower = color.RGBA{R: 0x6a, G: 0x79, B: 0xf7, A:0xff }
	
	// 766 blue violet #5d06e9 
	BlueViolet = color.RGBA{R: 0x5d, G: 0x06, B: 0xe9, A:0xff }
	
	// 767 chocolate #3d1c02 
	Chocolate = color.RGBA{R: 0x3d, G: 0x1c, B: 0x02, A:0xff }
	
	// 768 greyish green #82a67d 
	GreyishGreen = color.RGBA{R: 0x82, G: 0xa6, B: 0x7d, A:0xff }
	
	// 769 scarlet #be0119 
	Scarlet = color.RGBA{R: 0xbe, G: 0x01, B: 0x19, A:0xff }
	
	// 770 green yellow #c9ff27 
	GreenYellow = color.RGBA{R: 0xc9, G: 0xff, B: 0x27, A:0xff }
	
	// 771 dark olive #373e02 
	DarkOlive = color.RGBA{R: 0x37, G: 0x3e, B: 0x02, A:0xff }
	
	// 772 sienna #a9561e 
	Sienna = color.RGBA{R: 0xa9, G: 0x56, B: 0x1e, A:0xff }
	
	// 773 pastel purple #caa0ff 
	PastelPurple = color.RGBA{R: 0xca, G: 0xa0, B: 0xff, A:0xff }
	
	// 774 terracotta #ca6641 
	Terracotta = color.RGBA{R: 0xca, G: 0x66, B: 0x41, A:0xff }
	
	// 775 aqua blue #02d8e9 
	AquaBlue = color.RGBA{R: 0x02, G: 0xd8, B: 0xe9, A:0xff }
	
	// 776 sage green #88b378 
	SageGreen = color.RGBA{R: 0x88, G: 0xb3, B: 0x78, A:0xff }
	
	// 777 blood red #980002 
	BloodRed = color.RGBA{R: 0x98, G: 0x00, B: 0x02, A:0xff }
	
	// 778 deep pink #cb0162 
	DeepPink = color.RGBA{R: 0xcb, G: 0x01, B: 0x62, A:0xff }
	
	// 779 grass #5cac2d 
	Grass = color.RGBA{R: 0x5c, G: 0xac, B: 0x2d, A:0xff }
	
	// 780 moss #769958 
	Moss = color.RGBA{R: 0x76, G: 0x99, B: 0x58, A:0xff }
	
	// 781 pastel blue #a2bffe 
	PastelBlue = color.RGBA{R: 0xa2, G: 0xbf, B: 0xfe, A:0xff }
	
	// 782 bluish green #10a674 
	BluishGreen = color.RGBA{R: 0x10, G: 0xa6, B: 0x74, A:0xff }
	
	// 783 green blue #06b48b 
	GreenBlue = color.RGBA{R: 0x06, G: 0xb4, B: 0x8b, A:0xff }
	
	// 784 dark tan #af884a 
	DarkTan = color.RGBA{R: 0xaf, G: 0x88, B: 0x4a, A:0xff }
	
	// 785 greenish blue #0b8b87 
	GreenishBlue = color.RGBA{R: 0x0b, G: 0x8b, B: 0x87, A:0xff }
	
	// 786 pale orange #ffa756 
	PaleOrange = color.RGBA{R: 0xff, G: 0xa7, B: 0x56, A:0xff }
	
	// 787 vomit #a2a415 
	Vomit = color.RGBA{R: 0xa2, G: 0xa4, B: 0x15, A:0xff }
	
	// 788 forrest green #154406 
	ForrestGreen = color.RGBA{R: 0x15, G: 0x44, B: 0x06, A:0xff }
	
	// 789 dark lavender #856798 
	DarkLavender = color.RGBA{R: 0x85, G: 0x67, B: 0x98, A:0xff }
	
	// 790 dark violet #34013f 
	DarkViolet = color.RGBA{R: 0x34, G: 0x01, B: 0x3f, A:0xff }
	
	// 791 purple blue #632de9 
	PurpleBlue = color.RGBA{R: 0x63, G: 0x2d, B: 0xe9, A:0xff }
	
	// 792 dark cyan #0a888a 
	DarkCyan = color.RGBA{R: 0x0a, G: 0x88, B: 0x8a, A:0xff }
	
	// 793 olive drab #6f7632 
	OliveDrab = color.RGBA{R: 0x6f, G: 0x76, B: 0x32, A:0xff }
	
	// 794 pinkish #d46a7e 
	Pinkish = color.RGBA{R: 0xd4, G: 0x6a, B: 0x7e, A:0xff }
	
	// 795 cobalt #1e488f 
	Cobalt = color.RGBA{R: 0x1e, G: 0x48, B: 0x8f, A:0xff }
	
	// 796 neon purple #bc13fe 
	NeonPurple = color.RGBA{R: 0xbc, G: 0x13, B: 0xfe, A:0xff }
	
	// 797 light turquoise #7ef4cc 
	LightTurquoise = color.RGBA{R: 0x7e, G: 0xf4, B: 0xcc, A:0xff }
	
	// 798 apple green #76cd26 
	AppleGreen = color.RGBA{R: 0x76, G: 0xcd, B: 0x26, A:0xff }
	
	// 799 dull green #74a662 
	DullGreen = color.RGBA{R: 0x74, G: 0xa6, B: 0x62, A:0xff }
	
	// 800 wine #80013f 
	Wine = color.RGBA{R: 0x80, G: 0x01, B: 0x3f, A:0xff }
	
	// 801 powder blue #b1d1fc 
	PowderBlue = color.RGBA{R: 0xb1, G: 0xd1, B: 0xfc, A:0xff }
	
	// 802 off white #ffffe4 
	OffWhite = color.RGBA{R: 0xff, G: 0xff, B: 0xe4, A:0xff }
	
	// 803 electric blue #0652ff 
	ElectricBlue = color.RGBA{R: 0x06, G: 0x52, B: 0xff, A:0xff }
	
	// 804 dark turquoise #045c5a 
	DarkTurquoise = color.RGBA{R: 0x04, G: 0x5c, B: 0x5a, A:0xff }
	
	// 805 blue purple #5729ce 
	BluePurple = color.RGBA{R: 0x57, G: 0x29, B: 0xce, A:0xff }
	
	// 806 azure #069af3 
	Azure = color.RGBA{R: 0x06, G: 0x9a, B: 0xf3, A:0xff }
	
	// 807 bright red #ff000d
	BrightRed = color.RGBA{R: 0xff, G: 0x00, B: 0x0d, A:0xff }
	
	// 808 pinkish red #f10c45 
	PinkishRed = color.RGBA{R: 0xf1, G: 0x0c, B: 0x45, A:0xff }
	
	// 809 cornflower blue #5170d7 
	CornflowerBlue = color.RGBA{R: 0x51, G: 0x70, B: 0xd7, A:0xff }
	
	// 810 light olive #acbf69 
	LightOlive = color.RGBA{R: 0xac, G: 0xbf, B: 0x69, A:0xff }
	
	// 811 grape #6c3461 
	Grape = color.RGBA{R: 0x6c, G: 0x34, B: 0x61, A:0xff }
	
	// 812 greyish blue #5e819d 
	GreyishBlue = color.RGBA{R: 0x5e, G: 0x81, B: 0x9d, A:0xff }
	
	// 813 purplish blue #601ef9 
	PurplishBlue = color.RGBA{R: 0x60, G: 0x1e, B: 0xf9, A:0xff }
	
	// 814 yellowish green #b0dd16 
	YellowishGreen = color.RGBA{R: 0xb0, G: 0xdd, B: 0x16, A:0xff }
	
	// 815 greenish yellow #cdfd02 
	GreenishYellow = color.RGBA{R: 0xcd, G: 0xfd, B: 0x02, A:0xff }
	
	// 816 medium blue #2c6fbb 
	MediumBlue = color.RGBA{R: 0x2c, G: 0x6f, B: 0xbb, A:0xff }
	
	// 817 dusty rose #c0737a 
	DustyRose = color.RGBA{R: 0xc0, G: 0x73, B: 0x7a, A:0xff }
	
	// 818 light violet #d6b4fc 
	LightViolet = color.RGBA{R: 0xd6, G: 0xb4, B: 0xfc, A:0xff }
	
	// 819 midnight blue #020035 
	MidnightBlue = color.RGBA{R: 0x02, G: 0x00, B: 0x35, A:0xff }
	
	// 820 bluish purple #703be7 
	BluishPurple = color.RGBA{R: 0x70, G: 0x3b, B: 0xe7, A:0xff }
	
	// 821 red orange #fd3c06 
	RedOrange = color.RGBA{R: 0xfd, G: 0x3c, B: 0x06, A:0xff }
	
	// 822 dark magenta #960056 
	DarkMagenta = color.RGBA{R: 0x96, G: 0x00, B: 0x56, A:0xff }
	
	// 823 greenish #40a368 
	Greenish = color.RGBA{R: 0x40, G: 0xa3, B: 0x68, A:0xff }
	
	// 824 ocean blue #03719c 
	OceanBlue = color.RGBA{R: 0x03, G: 0x71, B: 0x9c, A:0xff }
	
	// 825 coral #fc5a50 
	Coral = color.RGBA{R: 0xfc, G: 0x5a, B: 0x50, A:0xff }
	
	// 826 cream #ffffc2 
	Cream = color.RGBA{R: 0xff, G: 0xff, B: 0xc2, A:0xff }
	
	// 827 reddish brown #7f2b0a 
	ReddishBrown = color.RGBA{R: 0x7f, G: 0x2b, B: 0x0a, A:0xff }
	
	// 828 burnt sienna #b04e0f 
	BurntSienna = color.RGBA{R: 0xb0, G: 0x4e, B: 0x0f, A:0xff }
	
	// 829 brick #a03623 
	Brick = color.RGBA{R: 0xa0, G: 0x36, B: 0x23, A:0xff }
	
	// 830 sage #87ae73 
	Sage = color.RGBA{R: 0x87, G: 0xae, B: 0x73, A:0xff }
	
	// 831 grey green #789b73 
	GreyGreen = color.RGBA{R: 0x78, G: 0x9b, B: 0x73, A:0xff }
	
	// 832 white #ffffff 
	White = color.RGBA{R: 0xff, G: 0xff, B: 0xff, A:0xff }
	
	// 833 robin's egg blue #98eff9 
	RobinsEggBlue = color.RGBA{R: 0x98, G: 0xef, B: 0xf9, A:0xff }
	
	// 834 moss green #658b38 
	MossGreen = color.RGBA{R: 0x65, G: 0x8b, B: 0x38, A:0xff }
	
	// 835 steel blue #5a7d9a 
	SteelBlue = color.RGBA{R: 0x5a, G: 0x7d, B: 0x9a, A:0xff }
	
	// 836 eggplant #380835 
	Eggplant = color.RGBA{R: 0x38, G: 0x08, B: 0x35, A:0xff }
	
	// 837 light yellow #fffe7a 
	LightYellow = color.RGBA{R: 0xff, G: 0xfe, B: 0x7a, A:0xff }
	
	// 838 leaf green #5ca904 
	LeafGreen = color.RGBA{R: 0x5c, G: 0xa9, B: 0x04, A:0xff }
	
	// 839 light grey #d8dcd6 
	LightGrey = color.RGBA{R: 0xd8, G: 0xdc, B: 0xd6, A:0xff }
	
	// 840 puke #a5a502 
	Puke = color.RGBA{R: 0xa5, G: 0xa5, B: 0x02, A:0xff }
	
	// 841 pinkish purple #d648d7 
	PinkishPurple = color.RGBA{R: 0xd6, G: 0x48, B: 0xd7, A:0xff }
	
	// 842 sea blue #047495 
	SeaBlue = color.RGBA{R: 0x04, G: 0x74, B: 0x95, A:0xff }
	
	// 843 pale purple #b790d4 
	PalePurple = color.RGBA{R: 0xb7, G: 0x90, B: 0xd4, A:0xff }
	
	// 844 slate blue #5b7c99 
	SlateBlue = color.RGBA{R: 0x5b, G: 0x7c, B: 0x99, A:0xff }
	
	// 845 blue grey #607c8e 
	BlueGrey = color.RGBA{R: 0x60, G: 0x7c, B: 0x8e, A:0xff }
	
	// 846 hunter green #0b4008 
	HunterGreen = color.RGBA{R: 0x0b, G: 0x40, B: 0x08, A:0xff }
	
	// 847 fuchsia #ed0dd9 
	Fuchsia = color.RGBA{R: 0xed, G: 0x0d, B: 0xd9, A:0xff }
	
	// 848 crimson #8c000f 
	Crimson = color.RGBA{R: 0x8c, G: 0x00, B: 0x0f, A:0xff }
	
	// 849 pale yellow #ffff84 
	PaleYellow = color.RGBA{R: 0xff, G: 0xff, B: 0x84, A:0xff }
	
	// 850 ochre #bf9005 
	Ochre = color.RGBA{R: 0xbf, G: 0x90, B: 0x05, A:0xff }
	
	// 851 mustard yellow #d2bd0a 
	MustardYellow = color.RGBA{R: 0xd2, G: 0xbd, B: 0x0a, A:0xff }
	
	// 852 light red #ff474c 
	LightRed = color.RGBA{R: 0xff, G: 0x47, B: 0x4c, A:0xff }
	
	// 853 cerulean #0485d1 
	Cerulean = color.RGBA{R: 0x04, G: 0x85, B: 0xd1, A:0xff }
	
	// 854 pale pink #ffcfdc 
	PalePink = color.RGBA{R: 0xff, G: 0xcf, B: 0xdc, A:0xff }
	
	// 855 deep blue #040273 
	DeepBlue = color.RGBA{R: 0x04, G: 0x02, B: 0x73, A:0xff }
	
	// 856 rust #a83c09 
	Rust = color.RGBA{R: 0xa8, G: 0x3c, B: 0x09, A:0xff }
	
	// 857 light teal #90e4c1 
	LightTeal = color.RGBA{R: 0x90, G: 0xe4, B: 0xc1, A:0xff }
	
	// 858 slate #516572 
	Slate = color.RGBA{R: 0x51, G: 0x65, B: 0x72, A:0xff }
	
	// 859 goldenrod #fac205 
	Goldenrod = color.RGBA{R: 0xfa, G: 0xc2, B: 0x05, A:0xff }
	
	// 860 dark yellow #d5b60a 
	DarkYellow = color.RGBA{R: 0xd5, G: 0xb6, B: 0x0a, A:0xff }
	
	// 861 dark grey #363737 
	DarkGrey = color.RGBA{R: 0x36, G: 0x37, B: 0x37, A:0xff }
	
	// 862 army green #4b5d16 
	ArmyGreen = color.RGBA{R: 0x4b, G: 0x5d, B: 0x16, A:0xff }
	
	// 863 grey blue #6b8ba4 
	GreyBlue = color.RGBA{R: 0x6b, G: 0x8b, B: 0xa4, A:0xff }
	
	// 864 seafoam #80f9ad 
	Seafoam = color.RGBA{R: 0x80, G: 0xf9, B: 0xad, A:0xff }
	
	// 865 puce #a57e52 
	Puce = color.RGBA{R: 0xa5, G: 0x7e, B: 0x52, A:0xff }
	
	// 866 spring green #a9f971 
	SpringGreen = color.RGBA{R: 0xa9, G: 0xf9, B: 0x71, A:0xff }
	
	// 867 dark orange #c65102 
	DarkOrange = color.RGBA{R: 0xc6, G: 0x51, B: 0x02, A:0xff }
	
	// 868 sand #e2ca76 
	Sand = color.RGBA{R: 0xe2, G: 0xca, B: 0x76, A:0xff }
	
	// 869 pastel green #b0ff9d 
	PastelGreen = color.RGBA{R: 0xb0, G: 0xff, B: 0x9d, A:0xff }
	
	// 870 mint #9ffeb0 
	Mint = color.RGBA{R: 0x9f, G: 0xfe, B: 0xb0, A:0xff }
	
	// 871 light orange #fdaa48 
	LightOrange = color.RGBA{R: 0xfd, G: 0xaa, B: 0x48, A:0xff }
	
	// 872 bright pink #fe01b1 
	BrightPink = color.RGBA{R: 0xfe, G: 0x01, B: 0xb1, A:0xff }
	
	// 873 chartreuse #c1f80a 
	Chartreuse = color.RGBA{R: 0xc1, G: 0xf8, B: 0x0a, A:0xff }
	
	// 874 deep purple #36013f 
	DeepPurple = color.RGBA{R: 0x36, G: 0x01, B: 0x3f, A:0xff }
	
	// 875 dark brown #341c02 
	DarkBrown = color.RGBA{R: 0x34, G: 0x1c, B: 0x02, A:0xff }
	
	// 876 taupe #b9a281 
	Taupe = color.RGBA{R: 0xb9, G: 0xa2, B: 0x81, A:0xff }
	
	// 877 pea green #8eab12 
	PeaGreen = color.RGBA{R: 0x8e, G: 0xab, B: 0x12, A:0xff }
	
	// 878 puke green #9aae07 
	PukeGreen = color.RGBA{R: 0x9a, G: 0xae, B: 0x07, A:0xff }
	
	// 879 kelly green #02ab2e 
	KellyGreen = color.RGBA{R: 0x02, G: 0xab, B: 0x2e, A:0xff }
	
	// 880 seafoam green #7af9ab 
	SeafoamGreen = color.RGBA{R: 0x7a, G: 0xf9, B: 0xab, A:0xff }
	
	// 881 blue green #137e6d 
	BlueGreen = color.RGBA{R: 0x13, G: 0x7e, B: 0x6d, A:0xff }
	
	// 882 khaki #aaa662 
	Khaki = color.RGBA{R: 0xaa, G: 0xa6, B: 0x62, A:0xff }
	
	// 883 burgundy #610023 
	Burgundy = color.RGBA{R: 0x61, G: 0x00, B: 0x23, A:0xff }
	
	// 884 dark teal #014d4e 
	DarkTeal = color.RGBA{R: 0x01, G: 0x4d, B: 0x4e, A:0xff }
	
	// 885 brick red #8f1402 
	BrickRed = color.RGBA{R: 0x8f, G: 0x14, B: 0x02, A:0xff }
	
	// 886 royal purple #4b006e 
	RoyalPurple = color.RGBA{R: 0x4b, G: 0x00, B: 0x6e, A:0xff }
	
	// 887 plum #580f41 
	Plum = color.RGBA{R: 0x58, G: 0x0f, B: 0x41, A:0xff }
	
	// 888 mint green #8fff9f 
	MintGreen = color.RGBA{R: 0x8f, G: 0xff, B: 0x9f, A:0xff }
	
	// 889 gold #dbb40c 
	Gold = color.RGBA{R: 0xdb, G: 0xb4, B: 0x0c, A:0xff }
	
	// 890 baby blue #a2cffe 
	BabyBlue = color.RGBA{R: 0xa2, G: 0xcf, B: 0xfe, A:0xff }
	
	// 891 yellow green #c0fb2d 
	YellowGreen = color.RGBA{R: 0xc0, G: 0xfb, B: 0x2d, A:0xff }
	
	// 892 bright purple #be03fd 
	BrightPurple = color.RGBA{R: 0xbe, G: 0x03, B: 0xfd, A:0xff }
	
	// 893 dark red #840000 
	DarkRed = color.RGBA{R: 0x84, G: 0x00, B: 0x00, A:0xff }
	
	// 894 pale blue #d0fefe 
	PaleBlue = color.RGBA{R: 0xd0, G: 0xfe, B: 0xfe, A:0xff }
	
	// 895 grass green #3f9b0b 
	GrassGreen = color.RGBA{R: 0x3f, G: 0x9b, B: 0x0b, A:0xff }
	
	// 896 navy #01153e 
	Navy = color.RGBA{R: 0x01, G: 0x15, B: 0x3e, A:0xff }
	
	// 897 aquamarine #04d8b2 
	Aquamarine = color.RGBA{R: 0x04, G: 0xd8, B: 0xb2, A:0xff }
	
	// 898 burnt orange #c04e01 
	BurntOrange = color.RGBA{R: 0xc0, G: 0x4e, B: 0x01, A:0xff }
	
	// 899 neon green #0cff0c 
	NeonGreen = color.RGBA{R: 0x0c, G: 0xff, B: 0x0c, A:0xff }
	
	// 900 bright blue #0165fc 
	BrightBlue = color.RGBA{R: 0x01, G: 0x65, B: 0xfc, A:0xff }
	
	// 901 rose #cf6275 
	Rose = color.RGBA{R: 0xcf, G: 0x62, B: 0x75, A:0xff }
	
	// 902 light pink #ffd1df 
	LightPink = color.RGBA{R: 0xff, G: 0xd1, B: 0xdf, A:0xff }
	
	// 903 mustard #ceb301 
	Mustard = color.RGBA{R: 0xce, G: 0xb3, B: 0x01, A:0xff }
	
	// 904 indigo #380282 
	Indigo = color.RGBA{R: 0x38, G: 0x02, B: 0x82, A:0xff }
	
	// 905 lime #aaff32 
	Lime = color.RGBA{R: 0xaa, G: 0xff, B: 0x32, A:0xff }
	
	// 906 sea green #53fca1 
	SeaGreen = color.RGBA{R: 0x53, G: 0xfc, B: 0xa1, A:0xff }
	
	// 907 periwinkle #8e82fe 
	Periwinkle = color.RGBA{R: 0x8e, G: 0x82, B: 0xfe, A:0xff }
	
	// 908 dark pink #cb416b 
	DarkPink = color.RGBA{R: 0xcb, G: 0x41, B: 0x6b, A:0xff }
	
	// 909 olive green #677a04 
	OliveGreen = color.RGBA{R: 0x67, G: 0x7a, B: 0x04, A:0xff }
	
	// 910 peach #ffb07c 
	Peach = color.RGBA{R: 0xff, G: 0xb0, B: 0x7c, A:0xff }
	
	// 911 pale green #c7fdb5 
	PaleGreen = color.RGBA{R: 0xc7, G: 0xfd, B: 0xb5, A:0xff }
	
	// 912 light brown #ad8150 
	LightBrown = color.RGBA{R: 0xad, G: 0x81, B: 0x50, A:0xff }
	
	// 913 hot pink #ff028d 
	HotPink = color.RGBA{R: 0xff, G: 0x02, B: 0x8d, A:0xff }
	
	// 914 black #000000 
	Black = color.RGBA{R: 0x00, G: 0x00, B: 0x00, A:0xff }
	
	// 915 lilac #cea2fd 
	Lilac = color.RGBA{R: 0xce, G: 0xa2, B: 0xfd, A:0xff }
	
	// 916 navy blue #001146 
	NavyBlue = color.RGBA{R: 0x00, G: 0x11, B: 0x46, A:0xff }
	
	// 917 royal blue #0504aa 
	RoyalBlue = color.RGBA{R: 0x05, G: 0x04, B: 0xaa, A:0xff }
	
	// 918 beige #e6daa6 
	Beige = color.RGBA{R: 0xe6, G: 0xda, B: 0xa6, A:0xff }
	
	// 919 salmon #ff796c 
	Salmon = color.RGBA{R: 0xff, G: 0x79, B: 0x6c, A:0xff }
	
	// 920 olive #6e750e 
	Olive = color.RGBA{R: 0x6e, G: 0x75, B: 0x0e, A:0xff }
	
	// 921 maroon #650021 
	Maroon = color.RGBA{R: 0x65, G: 0x00, B: 0x21, A:0xff }
	
	// 922 bright green #01ff07 
	BrightGreen = color.RGBA{R: 0x01, G: 0xff, B: 0x07, A:0xff }
	
	// 923 dark purple #35063e 
	DarkPurple = color.RGBA{R: 0x35, G: 0x06, B: 0x3e, A:0xff }
	
	// 924 mauve #ae7181 
	Mauve = color.RGBA{R: 0xae, G: 0x71, B: 0x81, A:0xff }
	
	// 925 forest green #06470c 
	ForestGreen = color.RGBA{R: 0x06, G: 0x47, B: 0x0c, A:0xff }
	
	// 926 aqua #13eac9 
	Aqua = color.RGBA{R: 0x13, G: 0xea, B: 0xc9, A:0xff }
	
	// 927 cyan #00ffff 
	Cyan = color.RGBA{R: 0x00, G: 0xff, B: 0xff, A:0xff }
	
	// 928 tan #d1b26f 
	Tan = color.RGBA{R: 0xd1, G: 0xb2, B: 0x6f, A:0xff }
	
	// 929 dark blue #00035b 
	DarkBlue = color.RGBA{R: 0x00, G: 0x03, B: 0x5b, A:0xff }
	
	// 930 lavender #c79fef 
	Lavender = color.RGBA{R: 0xc7, G: 0x9f, B: 0xef, A:0xff }
	
	// 931 turquoise #06c2ac 
	Turquoise = color.RGBA{R: 0x06, G: 0xc2, B: 0xac, A:0xff }
	
	// 932 dark green #033500 
	DarkGreen = color.RGBA{R: 0x03, G: 0x35, B: 0x00, A:0xff }
	
	// 933 violet #9a0eea 
	Violet = color.RGBA{R: 0x9a, G: 0x0e, B: 0xea, A:0xff }
	
	// 934 light purple #bf77f6 
	LightPurple = color.RGBA{R: 0xbf, G: 0x77, B: 0xf6, A:0xff }
	
	// 935 lime green #89fe05 
	LimeGreen = color.RGBA{R: 0x89, G: 0xfe, B: 0x05, A:0xff }
	
	// 936 grey #929591 
	Grey = color.RGBA{R: 0x92, G: 0x95, B: 0x91, A:0xff }
	
	// 937 sky blue #75bbfd 
	SkyBlue = color.RGBA{R: 0x75, G: 0xbb, B: 0xfd, A:0xff }
	
	// 938 yellow #ffff14 
	Yellow = color.RGBA{R: 0xff, G: 0xff, B: 0x14, A:0xff }
	
	// 939 magenta #c20078 
	Magenta = color.RGBA{R: 0xc2, G: 0x00, B: 0x78, A:0xff }
	
	// 940 light green #96f97b 
	LightGreen = color.RGBA{R: 0x96, G: 0xf9, B: 0x7b, A:0xff }
	
	// 941 orange #f97306 
	Orange = color.RGBA{R: 0xf9, G: 0x73, B: 0x06, A:0xff }
	
	// 942 teal #029386 
	Teal = color.RGBA{R: 0x02, G: 0x93, B: 0x86, A:0xff }
	
	// 943 light blue #95d0fc 
	LightBlue = color.RGBA{R: 0x95, G: 0xd0, B: 0xfc, A:0xff }
	
	// 944 red #e50000 
	Red = color.RGBA{R: 0xe5, G: 0x00, B: 0x00, A:0xff }
	
	// 945 brown #653700 
	Brown = color.RGBA{R: 0x65, G: 0x37, B: 0x00, A:0xff }
	
	// 946 pink #ff81c0 
	Pink = color.RGBA{R: 0xff, G: 0x81, B: 0xc0, A:0xff }
	
	// 947 blue #0343df 
	Blue = color.RGBA{R: 0x03, G: 0x43, B: 0xdf, A:0xff }
	
	// 948 green #15b01a 
	Green = color.RGBA{R: 0x15, G: 0xb0, B: 0x1a, A:0xff }
	
	// 949 purple #7e1e9c 
	Purple = color.RGBA{R: 0x7e, G: 0x1e, B: 0x9c, A:0xff }
	
)
